// Curated list of cities for the birds-eye-view quiz.
// tier: 1 = globally iconic, 2 = major, 3 = regional, 4 = niche
// commonsCategory overrides the default "Aerial photographs of <name>" when needed.
// wikipediaTitle overrides the default <name> for the Wikipedia REST API lookup.

export const cities = [
  // ---------- Europe ----------
  { name: "London", country: "United Kingdom", continent: "Europe", tier: 1 },
  { name: "Paris", country: "France", continent: "Europe", tier: 1 },
  { name: "Rome", country: "Italy", continent: "Europe", tier: 1 },
  { name: "Berlin", country: "Germany", continent: "Europe", tier: 1 },
  { name: "Madrid", country: "Spain", continent: "Europe", tier: 1 },
  { name: "Barcelona", country: "Spain", continent: "Europe", tier: 1 },
  { name: "Amsterdam", country: "Netherlands", continent: "Europe", tier: 1 },
  { name: "Vienna", country: "Austria", continent: "Europe", tier: 1 },
  { name: "Prague", country: "Czechia", continent: "Europe", tier: 1 },
  { name: "Athens", country: "Greece", continent: "Europe", tier: 1 },
  { name: "Lisbon", country: "Portugal", continent: "Europe", tier: 1 },
  { name: "Dublin", country: "Ireland", continent: "Europe", tier: 1 },
  { name: "Stockholm", country: "Sweden", continent: "Europe", tier: 1 },
  { name: "Copenhagen", country: "Denmark", continent: "Europe", tier: 1 },
  { name: "Helsinki", country: "Finland", continent: "Europe", tier: 2 },
  { name: "Oslo", country: "Norway", continent: "Europe", tier: 2 },
  { name: "Warsaw", country: "Poland", continent: "Europe", tier: 2 },
  { name: "Budapest", country: "Hungary", continent: "Europe", tier: 1 },
  { name: "Moscow", country: "Russia", continent: "Europe", tier: 1 },
  { name: "Saint Petersburg", country: "Russia", continent: "Europe", tier: 1 },
  { name: "Istanbul", country: "Turkey", continent: "Europe", tier: 1 },
  { name: "Munich", country: "Germany", continent: "Europe", tier: 2 },
  { name: "Hamburg", country: "Germany", continent: "Europe", tier: 2 },
  { name: "Frankfurt", country: "Germany", continent: "Europe", tier: 2, wikipediaTitle: "Frankfurt" },
  { name: "Cologne", country: "Germany", continent: "Europe", tier: 2 },
  { name: "Stuttgart", country: "Germany", continent: "Europe", tier: 3 },
  { name: "Düsseldorf", country: "Germany", continent: "Europe", tier: 3 },
  { name: "Milan", country: "Italy", continent: "Europe", tier: 1 },
  { name: "Naples", country: "Italy", continent: "Europe", tier: 2 },
  { name: "Florence", country: "Italy", continent: "Europe", tier: 1 },
  { name: "Venice", country: "Italy", continent: "Europe", tier: 1 },
  { name: "Bologna", country: "Italy", continent: "Europe", tier: 3 },
  { name: "Turin", country: "Italy", continent: "Europe", tier: 3 },
  { name: "Genoa", country: "Italy", continent: "Europe", tier: 3 },
  { name: "Palermo", country: "Italy", continent: "Europe", tier: 3 },
  { name: "Brussels", country: "Belgium", continent: "Europe", tier: 2 },
  { name: "Antwerp", country: "Belgium", continent: "Europe", tier: 3 },
  { name: "Zurich", country: "Switzerland", continent: "Europe", tier: 2 },
  { name: "Geneva", country: "Switzerland", continent: "Europe", tier: 2 },
  { name: "Bern", country: "Switzerland", continent: "Europe", tier: 3 },
  { name: "Edinburgh", country: "United Kingdom", continent: "Europe", tier: 1 },
  { name: "Manchester", country: "United Kingdom", continent: "Europe", tier: 2 },
  { name: "Birmingham", country: "United Kingdom", continent: "Europe", tier: 2 },
  { name: "Glasgow", country: "United Kingdom", continent: "Europe", tier: 2 },
  { name: "Liverpool", country: "United Kingdom", continent: "Europe", tier: 2 },
  { name: "Bristol", country: "United Kingdom", continent: "Europe", tier: 3 },
  { name: "Leeds", country: "United Kingdom", continent: "Europe", tier: 3 },
  { name: "Cardiff", country: "United Kingdom", continent: "Europe", tier: 3 },
  { name: "Belfast", country: "United Kingdom", continent: "Europe", tier: 3 },
  { name: "Newcastle upon Tyne", country: "United Kingdom", continent: "Europe", tier: 4 },
  { name: "Lyon", country: "France", continent: "Europe", tier: 2 },
  { name: "Marseille", country: "France", continent: "Europe", tier: 2 },
  { name: "Toulouse", country: "France", continent: "Europe", tier: 3 },
  { name: "Nice", country: "France", continent: "Europe", tier: 2, wikipediaTitle: "Nice" },
  { name: "Bordeaux", country: "France", continent: "Europe", tier: 3 },
  { name: "Strasbourg", country: "France", continent: "Europe", tier: 3 },
  { name: "Seville", country: "Spain", continent: "Europe", tier: 2, wikipediaTitle: "Seville" },
  { name: "Valencia", country: "Spain", continent: "Europe", tier: 2 },
  { name: "Bilbao", country: "Spain", continent: "Europe", tier: 3 },
  { name: "Malaga", country: "Spain", continent: "Europe", tier: 3, wikipediaTitle: "Málaga" },
  { name: "Granada", country: "Spain", continent: "Europe", tier: 3 },
  { name: "Porto", country: "Portugal", continent: "Europe", tier: 2 },
  { name: "Reykjavik", country: "Iceland", continent: "Europe", tier: 2, wikipediaTitle: "Reykjavík" },
  { name: "Bucharest", country: "Romania", continent: "Europe", tier: 2 },
  { name: "Sofia", country: "Bulgaria", continent: "Europe", tier: 2 },
  { name: "Belgrade", country: "Serbia", continent: "Europe", tier: 2 },
  { name: "Zagreb", country: "Croatia", continent: "Europe", tier: 3 },
  { name: "Ljubljana", country: "Slovenia", continent: "Europe", tier: 3 },
  { name: "Sarajevo", country: "Bosnia and Herzegovina", continent: "Europe", tier: 3 },
  { name: "Skopje", country: "North Macedonia", continent: "Europe", tier: 4 },
  { name: "Tirana", country: "Albania", continent: "Europe", tier: 4 },
  { name: "Tallinn", country: "Estonia", continent: "Europe", tier: 3 },
  { name: "Riga", country: "Latvia", continent: "Europe", tier: 3 },
  { name: "Vilnius", country: "Lithuania", continent: "Europe", tier: 3 },
  { name: "Minsk", country: "Belarus", continent: "Europe", tier: 3 },
  { name: "Kyiv", country: "Ukraine", continent: "Europe", tier: 2 },
  { name: "Lviv", country: "Ukraine", continent: "Europe", tier: 3 },
  { name: "Krakow", country: "Poland", continent: "Europe", tier: 2, wikipediaTitle: "Kraków" },
  { name: "Gdansk", country: "Poland", continent: "Europe", tier: 3, wikipediaTitle: "Gdańsk" },
  { name: "Wroclaw", country: "Poland", continent: "Europe", tier: 3, wikipediaTitle: "Wrocław" },
  { name: "Poznan", country: "Poland", continent: "Europe", tier: 4, wikipediaTitle: "Poznań" },
  { name: "Bratislava", country: "Slovakia", continent: "Europe", tier: 3 },
  { name: "Luxembourg City", country: "Luxembourg", continent: "Europe", tier: 4, wikipediaTitle: "Luxembourg City" },
  { name: "Monaco", country: "Monaco", continent: "Europe", tier: 2 },
  { name: "Valletta", country: "Malta", continent: "Europe", tier: 4 },
  { name: "Nicosia", country: "Cyprus", continent: "Europe", tier: 4 },
  { name: "Rotterdam", country: "Netherlands", continent: "Europe", tier: 3 },
  { name: "The Hague", country: "Netherlands", continent: "Europe", tier: 3 },
  { name: "Utrecht", country: "Netherlands", continent: "Europe", tier: 4 },
  { name: "Gothenburg", country: "Sweden", continent: "Europe", tier: 4 },
  { name: "Bergen", country: "Norway", continent: "Europe", tier: 4 },
  { name: "Aarhus", country: "Denmark", continent: "Europe", tier: 4 },

  // ---------- Asia ----------
  { name: "Tokyo", country: "Japan", continent: "Asia", tier: 1 },
  { name: "Osaka", country: "Japan", continent: "Asia", tier: 2 },
  { name: "Kyoto", country: "Japan", continent: "Asia", tier: 2 },
  { name: "Yokohama", country: "Japan", continent: "Asia", tier: 3 },
  { name: "Nagoya", country: "Japan", continent: "Asia", tier: 3 },
  { name: "Sapporo", country: "Japan", continent: "Asia", tier: 3 },
  { name: "Fukuoka", country: "Japan", continent: "Asia", tier: 4 },
  { name: "Hiroshima", country: "Japan", continent: "Asia", tier: 3 },
  { name: "Beijing", country: "China", continent: "Asia", tier: 1 },
  { name: "Shanghai", country: "China", continent: "Asia", tier: 1 },
  { name: "Hong Kong", country: "China", continent: "Asia", tier: 1 },
  { name: "Guangzhou", country: "China", continent: "Asia", tier: 2 },
  { name: "Shenzhen", country: "China", continent: "Asia", tier: 2 },
  { name: "Chengdu", country: "China", continent: "Asia", tier: 3 },
  { name: "Chongqing", country: "China", continent: "Asia", tier: 3 },
  { name: "Wuhan", country: "China", continent: "Asia", tier: 3 },
  { name: "Tianjin", country: "China", continent: "Asia", tier: 3 },
  { name: "Xi'an", country: "China", continent: "Asia", tier: 3 },
  { name: "Hangzhou", country: "China", continent: "Asia", tier: 3 },
  { name: "Nanjing", country: "China", continent: "Asia", tier: 3 },
  { name: "Macau", country: "China", continent: "Asia", tier: 2 },
  { name: "Taipei", country: "Taiwan", continent: "Asia", tier: 2 },
  { name: "Kaohsiung", country: "Taiwan", continent: "Asia", tier: 4 },
  { name: "Seoul", country: "South Korea", continent: "Asia", tier: 1 },
  { name: "Busan", country: "South Korea", continent: "Asia", tier: 3 },
  { name: "Incheon", country: "South Korea", continent: "Asia", tier: 4 },
  { name: "Pyongyang", country: "North Korea", continent: "Asia", tier: 3 },
  { name: "Singapore", country: "Singapore", continent: "Asia", tier: 1 },
  { name: "Kuala Lumpur", country: "Malaysia", continent: "Asia", tier: 2 },
  { name: "George Town", country: "Malaysia", continent: "Asia", tier: 4, wikipediaTitle: "George Town, Penang" },
  { name: "Bangkok", country: "Thailand", continent: "Asia", tier: 1 },
  { name: "Chiang Mai", country: "Thailand", continent: "Asia", tier: 4 },
  { name: "Jakarta", country: "Indonesia", continent: "Asia", tier: 2 },
  { name: "Surabaya", country: "Indonesia", continent: "Asia", tier: 4 },
  { name: "Bali", country: "Indonesia", continent: "Asia", tier: 3, wikipediaTitle: "Denpasar" },
  { name: "Manila", country: "Philippines", continent: "Asia", tier: 2 },
  { name: "Cebu City", country: "Philippines", continent: "Asia", tier: 4 },
  { name: "Ho Chi Minh City", country: "Vietnam", continent: "Asia", tier: 2 },
  { name: "Hanoi", country: "Vietnam", continent: "Asia", tier: 2 },
  { name: "Phnom Penh", country: "Cambodia", continent: "Asia", tier: 3 },
  { name: "Vientiane", country: "Laos", continent: "Asia", tier: 4 },
  { name: "Yangon", country: "Myanmar", continent: "Asia", tier: 3 },
  { name: "Mumbai", country: "India", continent: "Asia", tier: 1 },
  { name: "Delhi", country: "India", continent: "Asia", tier: 1 },
  { name: "Kolkata", country: "India", continent: "Asia", tier: 2 },
  { name: "Chennai", country: "India", continent: "Asia", tier: 2 },
  { name: "Bangalore", country: "India", continent: "Asia", tier: 2 },
  { name: "Hyderabad", country: "India", continent: "Asia", tier: 2 },
  { name: "Ahmedabad", country: "India", continent: "Asia", tier: 3 },
  { name: "Pune", country: "India", continent: "Asia", tier: 3 },
  { name: "Jaipur", country: "India", continent: "Asia", tier: 3 },
  { name: "Karachi", country: "Pakistan", continent: "Asia", tier: 2 },
  { name: "Lahore", country: "Pakistan", continent: "Asia", tier: 3 },
  { name: "Islamabad", country: "Pakistan", continent: "Asia", tier: 3 },
  { name: "Dhaka", country: "Bangladesh", continent: "Asia", tier: 2 },
  { name: "Colombo", country: "Sri Lanka", continent: "Asia", tier: 3 },
  { name: "Kathmandu", country: "Nepal", continent: "Asia", tier: 3 },
  { name: "Thimphu", country: "Bhutan", continent: "Asia", tier: 4 },
  { name: "Tehran", country: "Iran", continent: "Asia", tier: 2 },
  { name: "Isfahan", country: "Iran", continent: "Asia", tier: 4 },
  { name: "Baghdad", country: "Iraq", continent: "Asia", tier: 2 },
  { name: "Riyadh", country: "Saudi Arabia", continent: "Asia", tier: 2 },
  { name: "Jeddah", country: "Saudi Arabia", continent: "Asia", tier: 3 },
  { name: "Mecca", country: "Saudi Arabia", continent: "Asia", tier: 2 },
  { name: "Dubai", country: "United Arab Emirates", continent: "Asia", tier: 1 },
  { name: "Abu Dhabi", country: "United Arab Emirates", continent: "Asia", tier: 2 },
  { name: "Doha", country: "Qatar", continent: "Asia", tier: 2 },
  { name: "Kuwait City", country: "Kuwait", continent: "Asia", tier: 3 },
  { name: "Muscat", country: "Oman", continent: "Asia", tier: 3 },
  { name: "Manama", country: "Bahrain", continent: "Asia", tier: 4 },
  { name: "Beirut", country: "Lebanon", continent: "Asia", tier: 2 },
  { name: "Damascus", country: "Syria", continent: "Asia", tier: 2 },
  { name: "Amman", country: "Jordan", continent: "Asia", tier: 3 },
  { name: "Jerusalem", country: "Israel", continent: "Asia", tier: 1 },
  { name: "Tel Aviv", country: "Israel", continent: "Asia", tier: 2 },
  { name: "Ulaanbaatar", country: "Mongolia", continent: "Asia", tier: 3 },
  { name: "Almaty", country: "Kazakhstan", continent: "Asia", tier: 3 },
  { name: "Astana", country: "Kazakhstan", continent: "Asia", tier: 3 },
  { name: "Tashkent", country: "Uzbekistan", continent: "Asia", tier: 3 },
  { name: "Samarkand", country: "Uzbekistan", continent: "Asia", tier: 4 },
  { name: "Baku", country: "Azerbaijan", continent: "Asia", tier: 3 },
  { name: "Yerevan", country: "Armenia", continent: "Asia", tier: 3 },
  { name: "Tbilisi", country: "Georgia", continent: "Asia", tier: 3 },

  // ---------- Americas ----------
  { name: "New York City", country: "United States", continent: "Americas", tier: 1, wikipediaTitle: "New York City" },
  { name: "Los Angeles", country: "United States", continent: "Americas", tier: 1 },
  { name: "Chicago", country: "United States", continent: "Americas", tier: 1 },
  { name: "Houston", country: "United States", continent: "Americas", tier: 2 },
  { name: "Phoenix", country: "United States", continent: "Americas", tier: 3, wikipediaTitle: "Phoenix, Arizona" },
  { name: "Philadelphia", country: "United States", continent: "Americas", tier: 2 },
  { name: "San Antonio", country: "United States", continent: "Americas", tier: 3 },
  { name: "San Diego", country: "United States", continent: "Americas", tier: 2 },
  { name: "Dallas", country: "United States", continent: "Americas", tier: 2 },
  { name: "San Jose", country: "United States", continent: "Americas", tier: 3, wikipediaTitle: "San Jose, California" },
  { name: "Austin", country: "United States", continent: "Americas", tier: 3, wikipediaTitle: "Austin, Texas" },
  { name: "Jacksonville", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Jacksonville, Florida" },
  { name: "Columbus", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Columbus, Ohio" },
  { name: "Charlotte", country: "United States", continent: "Americas", tier: 3, wikipediaTitle: "Charlotte, North Carolina" },
  { name: "San Francisco", country: "United States", continent: "Americas", tier: 1 },
  { name: "Indianapolis", country: "United States", continent: "Americas", tier: 4 },
  { name: "Seattle", country: "United States", continent: "Americas", tier: 1 },
  { name: "Denver", country: "United States", continent: "Americas", tier: 2 },
  { name: "Washington, D.C.", country: "United States", continent: "Americas", tier: 1, wikipediaTitle: "Washington, D.C." },
  { name: "Boston", country: "United States", continent: "Americas", tier: 1 },
  { name: "Nashville", country: "United States", continent: "Americas", tier: 3, wikipediaTitle: "Nashville, Tennessee" },
  { name: "Baltimore", country: "United States", continent: "Americas", tier: 3 },
  { name: "Portland", country: "United States", continent: "Americas", tier: 2, wikipediaTitle: "Portland, Oregon" },
  { name: "Las Vegas", country: "United States", continent: "Americas", tier: 1 },
  { name: "Miami", country: "United States", continent: "Americas", tier: 1 },
  { name: "Atlanta", country: "United States", continent: "Americas", tier: 2 },
  { name: "Detroit", country: "United States", continent: "Americas", tier: 2 },
  { name: "Minneapolis", country: "United States", continent: "Americas", tier: 3 },
  { name: "Tampa", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Tampa, Florida" },
  { name: "New Orleans", country: "United States", continent: "Americas", tier: 2 },
  { name: "Pittsburgh", country: "United States", continent: "Americas", tier: 3 },
  { name: "Cincinnati", country: "United States", continent: "Americas", tier: 4 },
  { name: "Cleveland", country: "United States", continent: "Americas", tier: 3, wikipediaTitle: "Cleveland" },
  { name: "St. Louis", country: "United States", continent: "Americas", tier: 3 },
  { name: "Kansas City", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Kansas City, Missouri" },
  { name: "Salt Lake City", country: "United States", continent: "Americas", tier: 3 },
  { name: "Honolulu", country: "United States", continent: "Americas", tier: 2 },
  { name: "Anchorage", country: "United States", continent: "Americas", tier: 4 },
  { name: "Toronto", country: "Canada", continent: "Americas", tier: 1 },
  { name: "Vancouver", country: "Canada", continent: "Americas", tier: 1 },
  { name: "Montreal", country: "Canada", continent: "Americas", tier: 1 },
  { name: "Calgary", country: "Canada", continent: "Americas", tier: 3 },
  { name: "Ottawa", country: "Canada", continent: "Americas", tier: 2 },
  { name: "Edmonton", country: "Canada", continent: "Americas", tier: 3 },
  { name: "Winnipeg", country: "Canada", continent: "Americas", tier: 4 },
  { name: "Quebec City", country: "Canada", continent: "Americas", tier: 3 },
  { name: "Halifax", country: "Canada", continent: "Americas", tier: 4, wikipediaTitle: "Halifax, Nova Scotia" },
  { name: "Mexico City", country: "Mexico", continent: "Americas", tier: 1 },
  { name: "Guadalajara", country: "Mexico", continent: "Americas", tier: 3 },
  { name: "Monterrey", country: "Mexico", continent: "Americas", tier: 3 },
  { name: "Tijuana", country: "Mexico", continent: "Americas", tier: 3 },
  { name: "Cancun", country: "Mexico", continent: "Americas", tier: 3, wikipediaTitle: "Cancún" },
  { name: "Puebla", country: "Mexico", continent: "Americas", tier: 4 },
  { name: "Oaxaca", country: "Mexico", continent: "Americas", tier: 4, wikipediaTitle: "Oaxaca City" },
  { name: "São Paulo", country: "Brazil", continent: "Americas", tier: 1 },
  { name: "Rio de Janeiro", country: "Brazil", continent: "Americas", tier: 1 },
  { name: "Brasília", country: "Brazil", continent: "Americas", tier: 2 },
  { name: "Salvador", country: "Brazil", continent: "Americas", tier: 3, wikipediaTitle: "Salvador, Bahia" },
  { name: "Fortaleza", country: "Brazil", continent: "Americas", tier: 3 },
  { name: "Belo Horizonte", country: "Brazil", continent: "Americas", tier: 3 },
  { name: "Manaus", country: "Brazil", continent: "Americas", tier: 3 },
  { name: "Porto Alegre", country: "Brazil", continent: "Americas", tier: 3 },
  { name: "Recife", country: "Brazil", continent: "Americas", tier: 3 },
  { name: "Curitiba", country: "Brazil", continent: "Americas", tier: 4 },
  { name: "Buenos Aires", country: "Argentina", continent: "Americas", tier: 1 },
  { name: "Córdoba", country: "Argentina", continent: "Americas", tier: 4, wikipediaTitle: "Córdoba, Argentina" },
  { name: "Rosario", country: "Argentina", continent: "Americas", tier: 4 },
  { name: "Mendoza", country: "Argentina", continent: "Americas", tier: 4, wikipediaTitle: "Mendoza, Argentina" },
  { name: "Santiago", country: "Chile", continent: "Americas", tier: 2, wikipediaTitle: "Santiago" },
  { name: "Valparaíso", country: "Chile", continent: "Americas", tier: 4 },
  { name: "Lima", country: "Peru", continent: "Americas", tier: 2 },
  { name: "Cusco", country: "Peru", continent: "Americas", tier: 3 },
  { name: "La Paz", country: "Bolivia", continent: "Americas", tier: 3 },
  { name: "Sucre", country: "Bolivia", continent: "Americas", tier: 4 },
  { name: "Quito", country: "Ecuador", continent: "Americas", tier: 3 },
  { name: "Guayaquil", country: "Ecuador", continent: "Americas", tier: 4 },
  { name: "Bogotá", country: "Colombia", continent: "Americas", tier: 2 },
  { name: "Medellín", country: "Colombia", continent: "Americas", tier: 2 },
  { name: "Cartagena", country: "Colombia", continent: "Americas", tier: 3, wikipediaTitle: "Cartagena, Colombia" },
  { name: "Cali", country: "Colombia", continent: "Americas", tier: 4 },
  { name: "Caracas", country: "Venezuela", continent: "Americas", tier: 2 },
  { name: "Montevideo", country: "Uruguay", continent: "Americas", tier: 3 },
  { name: "Asunción", country: "Paraguay", continent: "Americas", tier: 4 },
  { name: "Panama City", country: "Panama", continent: "Americas", tier: 2 },
  { name: "San José", country: "Costa Rica", continent: "Americas", tier: 3, wikipediaTitle: "San José, Costa Rica" },
  { name: "Havana", country: "Cuba", continent: "Americas", tier: 2 },
  { name: "Santo Domingo", country: "Dominican Republic", continent: "Americas", tier: 3 },
  { name: "Kingston", country: "Jamaica", continent: "Americas", tier: 3, wikipediaTitle: "Kingston, Jamaica" },
  { name: "San Juan", country: "Puerto Rico", continent: "Americas", tier: 3, wikipediaTitle: "San Juan, Puerto Rico" },
  { name: "Nassau", country: "Bahamas", continent: "Americas", tier: 4, wikipediaTitle: "Nassau, Bahamas" },

  // ---------- Africa ----------
  { name: "Cairo", country: "Egypt", continent: "Africa", tier: 1 },
  { name: "Alexandria", country: "Egypt", continent: "Africa", tier: 3 },
  { name: "Lagos", country: "Nigeria", continent: "Africa", tier: 2 },
  { name: "Abuja", country: "Nigeria", continent: "Africa", tier: 4 },
  { name: "Kinshasa", country: "DR Congo", continent: "Africa", tier: 3 },
  { name: "Johannesburg", country: "South Africa", continent: "Africa", tier: 1 },
  { name: "Cape Town", country: "South Africa", continent: "Africa", tier: 1 },
  { name: "Durban", country: "South Africa", continent: "Africa", tier: 3 },
  { name: "Pretoria", country: "South Africa", continent: "Africa", tier: 3 },
  { name: "Nairobi", country: "Kenya", continent: "Africa", tier: 2 },
  { name: "Mombasa", country: "Kenya", continent: "Africa", tier: 4 },
  { name: "Addis Ababa", country: "Ethiopia", continent: "Africa", tier: 3 },
  { name: "Algiers", country: "Algeria", continent: "Africa", tier: 3 },
  { name: "Casablanca", country: "Morocco", continent: "Africa", tier: 2 },
  { name: "Marrakesh", country: "Morocco", continent: "Africa", tier: 2 },
  { name: "Rabat", country: "Morocco", continent: "Africa", tier: 3 },
  { name: "Fez", country: "Morocco", continent: "Africa", tier: 4 },
  { name: "Tunis", country: "Tunisia", continent: "Africa", tier: 3 },
  { name: "Tripoli", country: "Libya", continent: "Africa", tier: 3 },
  { name: "Khartoum", country: "Sudan", continent: "Africa", tier: 3 },
  { name: "Dakar", country: "Senegal", continent: "Africa", tier: 3 },
  { name: "Abidjan", country: "Ivory Coast", continent: "Africa", tier: 3 },
  { name: "Accra", country: "Ghana", continent: "Africa", tier: 3 },
  { name: "Lusaka", country: "Zambia", continent: "Africa", tier: 4 },
  { name: "Harare", country: "Zimbabwe", continent: "Africa", tier: 3 },
  { name: "Maputo", country: "Mozambique", continent: "Africa", tier: 4 },
  { name: "Luanda", country: "Angola", continent: "Africa", tier: 3 },
  { name: "Dar es Salaam", country: "Tanzania", continent: "Africa", tier: 3 },
  { name: "Kampala", country: "Uganda", continent: "Africa", tier: 3 },
  { name: "Kigali", country: "Rwanda", continent: "Africa", tier: 3 },
  { name: "Antananarivo", country: "Madagascar", continent: "Africa", tier: 4 },
  { name: "Windhoek", country: "Namibia", continent: "Africa", tier: 4 },
  { name: "Gaborone", country: "Botswana", continent: "Africa", tier: 4 },

  // ---------- Oceania ----------
  { name: "Sydney", country: "Australia", continent: "Oceania", tier: 1 },
  { name: "Melbourne", country: "Australia", continent: "Oceania", tier: 1 },
  { name: "Brisbane", country: "Australia", continent: "Oceania", tier: 2 },
  { name: "Perth", country: "Australia", continent: "Oceania", tier: 2, wikipediaTitle: "Perth" },
  { name: "Adelaide", country: "Australia", continent: "Oceania", tier: 3 },
  { name: "Canberra", country: "Australia", continent: "Oceania", tier: 2 },
  { name: "Hobart", country: "Australia", continent: "Oceania", tier: 4 },
  { name: "Gold Coast", country: "Australia", continent: "Oceania", tier: 3, wikipediaTitle: "Gold Coast, Queensland" },
  { name: "Auckland", country: "New Zealand", continent: "Oceania", tier: 2 },
  { name: "Wellington", country: "New Zealand", continent: "Oceania", tier: 3 },
  { name: "Christchurch", country: "New Zealand", continent: "Oceania", tier: 3 },
  { name: "Suva", country: "Fiji", continent: "Oceania", tier: 4 },
  { name: "Port Moresby", country: "Papua New Guinea", continent: "Oceania", tier: 4 },
  { name: "Honiara", country: "Solomon Islands", continent: "Oceania", tier: 4 },
  { name: "Apia", country: "Samoa", continent: "Oceania", tier: 4 },

  // ---------- Additional Europe ----------
  { name: "Salzburg", country: "Austria", continent: "Europe", tier: 3 },
  { name: "Innsbruck", country: "Austria", continent: "Europe", tier: 4 },
  { name: "Graz", country: "Austria", continent: "Europe", tier: 4 },
  { name: "Linz", country: "Austria", continent: "Europe", tier: 4 },
  { name: "Heidelberg", country: "Germany", continent: "Europe", tier: 3 },
  { name: "Dresden", country: "Germany", continent: "Europe", tier: 3 },
  { name: "Leipzig", country: "Germany", continent: "Europe", tier: 3 },
  { name: "Hannover", country: "Germany", continent: "Europe", tier: 4 },
  { name: "Bremen", country: "Germany", continent: "Europe", tier: 4 },
  { name: "Nuremberg", country: "Germany", continent: "Europe", tier: 3 },
  { name: "Montpellier", country: "France", continent: "Europe", tier: 4 },
  { name: "Rennes", country: "France", continent: "Europe", tier: 4 },
  { name: "Lille", country: "France", continent: "Europe", tier: 4 },
  { name: "Nantes", country: "France", continent: "Europe", tier: 4 },
  { name: "Catania", country: "Italy", continent: "Europe", tier: 4 },
  { name: "Verona", country: "Italy", continent: "Europe", tier: 4 },
  { name: "Padua", country: "Italy", continent: "Europe", tier: 4 },
  { name: "Pisa", country: "Italy", continent: "Europe", tier: 4 },
  { name: "Cluj-Napoca", country: "Romania", continent: "Europe", tier: 4 },
  { name: "Plovdiv", country: "Bulgaria", continent: "Europe", tier: 4 },
  { name: "Novi Sad", country: "Serbia", continent: "Europe", tier: 4 },
  { name: "Brno", country: "Czechia", continent: "Europe", tier: 4 },
  { name: "Pécs", country: "Hungary", continent: "Europe", tier: 4 },
  { name: "Debrecen", country: "Hungary", continent: "Europe", tier: 4 },
  { name: "Ghent", country: "Belgium", continent: "Europe", tier: 3 },
  { name: "Bruges", country: "Belgium", continent: "Europe", tier: 3 },
  { name: "Liège", country: "Belgium", continent: "Europe", tier: 4 },
  { name: "Basel", country: "Switzerland", continent: "Europe", tier: 3 },
  { name: "Lausanne", country: "Switzerland", continent: "Europe", tier: 4 },
  { name: "Cork", country: "Ireland", continent: "Europe", tier: 4 },
  { name: "Galway", country: "Ireland", continent: "Europe", tier: 4 },
  { name: "Aberdeen", country: "United Kingdom", continent: "Europe", tier: 4 },
  { name: "Sheffield", country: "United Kingdom", continent: "Europe", tier: 4 },
  { name: "Nottingham", country: "United Kingdom", continent: "Europe", tier: 4 },
  { name: "Trondheim", country: "Norway", continent: "Europe", tier: 4 },
  { name: "Stavanger", country: "Norway", continent: "Europe", tier: 4 },
  { name: "Malmö", country: "Sweden", continent: "Europe", tier: 4 },
  { name: "Uppsala", country: "Sweden", continent: "Europe", tier: 4 },
  { name: "Tampere", country: "Finland", continent: "Europe", tier: 4 },
  { name: "Turku", country: "Finland", continent: "Europe", tier: 4 },
  { name: "Odense", country: "Denmark", continent: "Europe", tier: 4 },

  // ---------- Additional Asia ----------
  { name: "Kobe", country: "Japan", continent: "Asia", tier: 3 },
  { name: "Sendai", country: "Japan", continent: "Asia", tier: 4 },
  { name: "Kanazawa", country: "Japan", continent: "Asia", tier: 4 },
  { name: "Nara", country: "Japan", continent: "Asia", tier: 4 },
  { name: "Suzhou", country: "China", continent: "Asia", tier: 3 },
  { name: "Qingdao", country: "China", continent: "Asia", tier: 4 },
  { name: "Dalian", country: "China", continent: "Asia", tier: 4 },
  { name: "Lucknow", country: "India", continent: "Asia", tier: 4 },
  { name: "Surat", country: "India", continent: "Asia", tier: 4 },
  { name: "Varanasi", country: "India", continent: "Asia", tier: 4 },
  { name: "Faisalabad", country: "Pakistan", continent: "Asia", tier: 4 },
  { name: "Multan", country: "Pakistan", continent: "Asia", tier: 4 },
  { name: "Chittagong", country: "Bangladesh", continent: "Asia", tier: 4 },
  { name: "Bandung", country: "Indonesia", continent: "Asia", tier: 4 },
  { name: "Medan", country: "Indonesia", continent: "Asia", tier: 4 },
  { name: "Davao", country: "Philippines", continent: "Asia", tier: 4, wikipediaTitle: "Davao City" },
  { name: "Da Nang", country: "Vietnam", continent: "Asia", tier: 4 },
  { name: "Mandalay", country: "Myanmar", continent: "Asia", tier: 4 },
  { name: "Mashhad", country: "Iran", continent: "Asia", tier: 4 },
  { name: "Shiraz", country: "Iran", continent: "Asia", tier: 4 },
  { name: "Aleppo", country: "Syria", continent: "Asia", tier: 4 },
  { name: "Haifa", country: "Israel", continent: "Asia", tier: 4 },
  { name: "Bukhara", country: "Uzbekistan", continent: "Asia", tier: 4 },
  { name: "Bishkek", country: "Kyrgyzstan", continent: "Asia", tier: 4 },
  { name: "Dushanbe", country: "Tajikistan", continent: "Asia", tier: 4 },
  { name: "Ashgabat", country: "Turkmenistan", continent: "Asia", tier: 4 },

  // ---------- Additional Americas ----------
  { name: "Memphis", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Memphis, Tennessee" },
  { name: "Milwaukee", country: "United States", continent: "Americas", tier: 4 },
  { name: "Albuquerque", country: "United States", continent: "Americas", tier: 4 },
  { name: "Oklahoma City", country: "United States", continent: "Americas", tier: 4 },
  { name: "Tucson", country: "United States", continent: "Americas", tier: 4 },
  { name: "Sacramento", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Sacramento, California" },
  { name: "Fresno", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Fresno, California" },
  { name: "Buffalo", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Buffalo, New York" },
  { name: "Saskatoon", country: "Canada", continent: "Americas", tier: 4 },
  { name: "Hamilton", country: "Canada", continent: "Americas", tier: 4, wikipediaTitle: "Hamilton, Ontario" },
  { name: "Victoria", country: "Canada", continent: "Americas", tier: 4, wikipediaTitle: "Victoria, British Columbia" },
  { name: "Mérida", country: "Mexico", continent: "Americas", tier: 4, wikipediaTitle: "Mérida, Yucatán" },
  { name: "León", country: "Mexico", continent: "Americas", tier: 4, wikipediaTitle: "León, Guanajuato" },
  { name: "Belém", country: "Brazil", continent: "Americas", tier: 4 },
  { name: "Goiânia", country: "Brazil", continent: "Americas", tier: 4 },
  { name: "Vitória", country: "Brazil", continent: "Americas", tier: 4, wikipediaTitle: "Vitória, Espírito Santo" },
  { name: "La Plata", country: "Argentina", continent: "Americas", tier: 4 },
  { name: "Mar del Plata", country: "Argentina", continent: "Americas", tier: 4 },
  { name: "Antofagasta", country: "Chile", continent: "Americas", tier: 4 },
  { name: "Concepción", country: "Chile", continent: "Americas", tier: 4, wikipediaTitle: "Concepción, Chile" },
  { name: "Arequipa", country: "Peru", continent: "Americas", tier: 4 },
  { name: "Trujillo", country: "Peru", continent: "Americas", tier: 4, wikipediaTitle: "Trujillo, Peru" },
  { name: "Barranquilla", country: "Colombia", continent: "Americas", tier: 4 },
  { name: "Bucaramanga", country: "Colombia", continent: "Americas", tier: 4 },
  { name: "Maracaibo", country: "Venezuela", continent: "Americas", tier: 4 },

  // ---------- Additional Africa ----------
  { name: "Port Harcourt", country: "Nigeria", continent: "Africa", tier: 4 },
  { name: "Ibadan", country: "Nigeria", continent: "Africa", tier: 4 },
  { name: "Lubumbashi", country: "DR Congo", continent: "Africa", tier: 4 },
  { name: "Bamako", country: "Mali", continent: "Africa", tier: 4 },
  { name: "Niamey", country: "Niger", continent: "Africa", tier: 4 },
  { name: "Ouagadougou", country: "Burkina Faso", continent: "Africa", tier: 4 },
  { name: "Lomé", country: "Togo", continent: "Africa", tier: 4 },
  { name: "Cotonou", country: "Benin", continent: "Africa", tier: 4 },
  { name: "Conakry", country: "Guinea", continent: "Africa", tier: 4 },
  { name: "Freetown", country: "Sierra Leone", continent: "Africa", tier: 4 },
  { name: "Yaoundé", country: "Cameroon", continent: "Africa", tier: 4 },
  { name: "Douala", country: "Cameroon", continent: "Africa", tier: 4 },
  { name: "Brazzaville", country: "Republic of the Congo", continent: "Africa", tier: 4 },
  { name: "Libreville", country: "Gabon", continent: "Africa", tier: 4 },

  // ---------- Additional Oceania ----------
  { name: "Newcastle", country: "Australia", continent: "Oceania", tier: 4, wikipediaTitle: "Newcastle, New South Wales" },
  { name: "Wollongong", country: "Australia", continent: "Oceania", tier: 4 },
  { name: "Geelong", country: "Australia", continent: "Oceania", tier: 4 },
  { name: "Darwin", country: "Australia", continent: "Oceania", tier: 4, wikipediaTitle: "Darwin, Northern Territory" },
  { name: "Dunedin", country: "New Zealand", continent: "Oceania", tier: 4 },
  { name: "Tauranga", country: "New Zealand", continent: "Oceania", tier: 4 },
  { name: "Nouméa", country: "New Caledonia", continent: "Oceania", tier: 4 },
  { name: "Pago Pago", country: "American Samoa", continent: "Oceania", tier: 4 },
  { name: "Papeete", country: "French Polynesia", continent: "Oceania", tier: 4 },
];

// ---------------------------------------------------------------------------
// Expansion batch (target ~1000 cities). Compact [name, country, continent,
// tier] rows, pushed onto the list above before ids are assigned. Cities that
// Wikimedia Commons has no usable aerial coverage for just produce zero images
// at build time and get dropped from the manifest.
// ---------------------------------------------------------------------------
const MORE = [
  // ---------- Europe ----------
  ["Brighton", "United Kingdom", "Europe", 3], ["Oxford", "United Kingdom", "Europe", 3],
  ["Cambridge", "United Kingdom", "Europe", 3], ["York", "United Kingdom", "Europe", 3],
  ["Bath", "United Kingdom", "Europe", 3], ["Leicester", "United Kingdom", "Europe", 4],
  ["Coventry", "United Kingdom", "Europe", 4], ["Plymouth", "United Kingdom", "Europe", 4],
  ["Southampton", "United Kingdom", "Europe", 3], ["Portsmouth", "United Kingdom", "Europe", 4],
  ["Swansea", "United Kingdom", "Europe", 4], ["Dundee", "United Kingdom", "Europe", 4],
  ["Norwich", "United Kingdom", "Europe", 4], ["Exeter", "United Kingdom", "Europe", 4],
  ["Inverness", "United Kingdom", "Europe", 4], ["Bournemouth", "United Kingdom", "Europe", 4],
  ["Blackpool", "United Kingdom", "Europe", 4], ["Stoke-on-Trent", "United Kingdom", "Europe", 4],
  ["Derby", "United Kingdom", "Europe", 4], ["Limerick", "Ireland", "Europe", 4],
  ["Dortmund", "Germany", "Europe", 3], ["Essen", "Germany", "Europe", 3],
  ["Duisburg", "Germany", "Europe", 4], ["Bonn", "Germany", "Europe", 3],
  ["Mannheim", "Germany", "Europe", 3], ["Karlsruhe", "Germany", "Europe", 3],
  ["Wiesbaden", "Germany", "Europe", 4], ["Münster", "Germany", "Europe", 3],
  ["Augsburg", "Germany", "Europe", 3], ["Freiburg", "Germany", "Europe", 3],
  ["Kiel", "Germany", "Europe", 4], ["Lübeck", "Germany", "Europe", 3],
  ["Erfurt", "Germany", "Europe", 4], ["Rostock", "Germany", "Europe", 4],
  ["Regensburg", "Germany", "Europe", 3], ["Würzburg", "Germany", "Europe", 4],
  ["Aachen", "Germany", "Europe", 4], ["Mainz", "Germany", "Europe", 4],
  ["Bielefeld", "Germany", "Europe", 4], ["Bochum", "Germany", "Europe", 4],
  ["Potsdam", "Germany", "Europe", 3], ["Ulm", "Germany", "Europe", 4],
  ["Grenoble", "France", "Europe", 3], ["Saint-Étienne", "France", "Europe", 4],
  ["Le Havre", "France", "Europe", 4], ["Reims", "France", "Europe", 3],
  ["Toulon", "France", "Europe", 4], ["Dijon", "France", "Europe", 3],
  ["Angers", "France", "Europe", 4], ["Nîmes", "France", "Europe", 4],
  ["Clermont-Ferrand", "France", "Europe", 4], ["Tours", "France", "Europe", 4],
  ["Avignon", "France", "Europe", 3], ["Aix-en-Provence", "France", "Europe", 3],
  ["Annecy", "France", "Europe", 3], ["Cannes", "France", "Europe", 3],
  ["Rouen", "France", "Europe", 4], ["Metz", "France", "Europe", 4],
  ["Nancy", "France", "Europe", 4], ["Caen", "France", "Europe", 4],
  ["Perpignan", "France", "Europe", 4], ["Brest", "France", "Europe", 4],
  ["La Rochelle", "France", "Europe", 4], ["Orléans", "France", "Europe", 4],
  ["Bari", "Italy", "Europe", 3], ["Cagliari", "Italy", "Europe", 3],
  ["Trieste", "Italy", "Europe", 3], ["Brescia", "Italy", "Europe", 4],
  ["Parma", "Italy", "Europe", 3], ["Modena", "Italy", "Europe", 4],
  ["Perugia", "Italy", "Europe", 3], ["Rimini", "Italy", "Europe", 3],
  ["Ravenna", "Italy", "Europe", 4], ["Bergamo", "Italy", "Europe", 3],
  ["Siena", "Italy", "Europe", 3], ["Lucca", "Italy", "Europe", 4],
  ["Como", "Italy", "Europe", 3], ["Trento", "Italy", "Europe", 4],
  ["Bolzano", "Italy", "Europe", 4], ["Salerno", "Italy", "Europe", 4],
  ["Ferrara", "Italy", "Europe", 4], ["Vicenza", "Italy", "Europe", 4],
  ["Ancona", "Italy", "Europe", 4], ["Reggio Calabria", "Italy", "Europe", 4],
  ["Zaragoza", "Spain", "Europe", 3], ["Murcia", "Spain", "Europe", 3],
  ["Palma", "Spain", "Europe", 3], ["Las Palmas", "Spain", "Europe", 3],
  ["Alicante", "Spain", "Europe", 3], ["Córdoba", "Spain", "Europe", 3],
  ["Valladolid", "Spain", "Europe", 4], ["Vigo", "Spain", "Europe", 4],
  ["Gijón", "Spain", "Europe", 4], ["San Sebastián", "Spain", "Europe", 3],
  ["Santander", "Spain", "Europe", 4], ["Salamanca", "Spain", "Europe", 3],
  ["Toledo", "Spain", "Europe", 3], ["Pamplona", "Spain", "Europe", 4],
  ["A Coruña", "Spain", "Europe", 4], ["Tarragona", "Spain", "Europe", 4],
  ["Cádiz", "Spain", "Europe", 4], ["Girona", "Spain", "Europe", 3],
  ["Marbella", "Spain", "Europe", 3], ["Santiago de Compostela", "Spain", "Europe", 3],
  ["Braga", "Portugal", "Europe", 4], ["Coimbra", "Portugal", "Europe", 3],
  ["Funchal", "Portugal", "Europe", 3], ["Faro", "Portugal", "Europe", 4],
  ["Sintra", "Portugal", "Europe", 4], ["Aveiro", "Portugal", "Europe", 4],
  ["Eindhoven", "Netherlands", "Europe", 4], ["Groningen", "Netherlands", "Europe", 4],
  ["Maastricht", "Netherlands", "Europe", 4], ["Haarlem", "Netherlands", "Europe", 4],
  ["Leiden", "Netherlands", "Europe", 4], ["Delft", "Netherlands", "Europe", 4],
  ["Nijmegen", "Netherlands", "Europe", 4], ["Leuven", "Belgium", "Europe", 4],
  ["Namur", "Belgium", "Europe", 4], ["Mechelen", "Belgium", "Europe", 4],
  ["Ostend", "Belgium", "Europe", 4], ["Lucerne", "Switzerland", "Europe", 3],
  ["Lugano", "Switzerland", "Europe", 4], ["Winterthur", "Switzerland", "Europe", 4],
  ["St. Gallen", "Switzerland", "Europe", 4], ["Klagenfurt", "Austria", "Europe", 4],
  ["Drammen", "Norway", "Europe", 4], ["Tromsø", "Norway", "Europe", 4],
  ["Kristiansand", "Norway", "Europe", 4], ["Ålesund", "Norway", "Europe", 4],
  ["Bodø", "Norway", "Europe", 4], ["Linköping", "Sweden", "Europe", 4],
  ["Örebro", "Sweden", "Europe", 4], ["Helsingborg", "Sweden", "Europe", 4],
  ["Lund", "Sweden", "Europe", 4], ["Västerås", "Sweden", "Europe", 4],
  ["Norrköping", "Sweden", "Europe", 4], ["Umeå", "Sweden", "Europe", 4],
  ["Aalborg", "Denmark", "Europe", 4], ["Esbjerg", "Denmark", "Europe", 4],
  ["Espoo", "Finland", "Europe", 4], ["Oulu", "Finland", "Europe", 4],
  ["Jyväskylä", "Finland", "Europe", 4], ["Tartu", "Estonia", "Europe", 4],
  ["Kaunas", "Lithuania", "Europe", 3], ["Klaipėda", "Lithuania", "Europe", 4],
  ["Lodz", "Poland", "Europe", 3], ["Szczecin", "Poland", "Europe", 3],
  ["Lublin", "Poland", "Europe", 3], ["Katowice", "Poland", "Europe", 3],
  ["Bydgoszcz", "Poland", "Europe", 4], ["Torun", "Poland", "Europe", 3],
  ["Sopot", "Poland", "Europe", 4], ["Gdynia", "Poland", "Europe", 4],
  ["Ostrava", "Czechia", "Europe", 3], ["Plzeň", "Czechia", "Europe", 3],
  ["Olomouc", "Czechia", "Europe", 4], ["Košice", "Slovakia", "Europe", 4],
  ["Szeged", "Hungary", "Europe", 4], ["Thessaloniki", "Greece", "Europe", 2],
  ["Heraklion", "Greece", "Europe", 3], ["Patras", "Greece", "Europe", 4],
  ["Rhodes", "Greece", "Europe", 3], ["Santorini", "Greece", "Europe", 3],
  ["Corfu", "Greece", "Europe", 4], ["Split", "Croatia", "Europe", 2],
  ["Dubrovnik", "Croatia", "Europe", 2], ["Rijeka", "Croatia", "Europe", 3],
  ["Zadar", "Croatia", "Europe", 3], ["Pula", "Croatia", "Europe", 4],
  ["Maribor", "Slovenia", "Europe", 4], ["Mostar", "Bosnia and Herzegovina", "Europe", 3],
  ["Banja Luka", "Bosnia and Herzegovina", "Europe", 4], ["Podgorica", "Montenegro", "Europe", 4],
  ["Kotor", "Montenegro", "Europe", 4], ["Pristina", "Kosovo", "Europe", 4],
  ["Niš", "Serbia", "Europe", 4], ["Ohrid", "North Macedonia", "Europe", 4],
  ["Varna", "Bulgaria", "Europe", 3], ["Burgas", "Bulgaria", "Europe", 4],
  ["Constanța", "Romania", "Europe", 3], ["Timișoara", "Romania", "Europe", 3],
  ["Iași", "Romania", "Europe", 3], ["Brașov", "Romania", "Europe", 3],
  ["Sibiu", "Romania", "Europe", 3], ["Chișinău", "Moldova", "Europe", 3],
  ["Novosibirsk", "Russia", "Europe", 2], ["Yekaterinburg", "Russia", "Europe", 2],
  ["Kazan", "Russia", "Europe", 2], ["Nizhny Novgorod", "Russia", "Europe", 3],
  ["Sochi", "Russia", "Europe", 2], ["Vladivostok", "Russia", "Europe", 3],
  ["Volgograd", "Russia", "Europe", 3], ["Samara", "Russia", "Europe", 3],
  ["Rostov-on-Don", "Russia", "Europe", 3], ["Krasnoyarsk", "Russia", "Europe", 3],
  ["Kaliningrad", "Russia", "Europe", 3], ["Irkutsk", "Russia", "Europe", 3],
  ["Odessa", "Ukraine", "Europe", 2], ["Kharkiv", "Ukraine", "Europe", 2],
  ["Dnipro", "Ukraine", "Europe", 3], ["Akureyri", "Iceland", "Europe", 4],

  // ---------- Asia ----------
  ["Ankara", "Turkey", "Asia", 2], ["Izmir", "Turkey", "Asia", 2],
  ["Bursa", "Turkey", "Asia", 3], ["Antalya", "Turkey", "Asia", 3],
  ["Adana", "Turkey", "Asia", 3], ["Konya", "Turkey", "Asia", 3],
  ["Gaziantep", "Turkey", "Asia", 3], ["Trabzon", "Turkey", "Asia", 4],
  ["Kayseri", "Turkey", "Asia", 4], ["Eskişehir", "Turkey", "Asia", 4],
  ["Kawasaki", "Japan", "Asia", 3], ["Saitama", "Japan", "Asia", 3],
  ["Chiba", "Japan", "Asia", 3], ["Kitakyushu", "Japan", "Asia", 3],
  ["Kumamoto", "Japan", "Asia", 3], ["Okayama", "Japan", "Asia", 3],
  ["Niigata", "Japan", "Asia", 3], ["Hamamatsu", "Japan", "Asia", 4],
  ["Shizuoka", "Japan", "Asia", 4], ["Nagasaki", "Japan", "Asia", 3],
  ["Kagoshima", "Japan", "Asia", 3], ["Naha", "Japan", "Asia", 3],
  ["Hakodate", "Japan", "Asia", 4], ["Matsuyama", "Japan", "Asia", 4],
  ["Shenyang", "China", "Asia", 2], ["Harbin", "China", "Asia", 2],
  ["Jinan", "China", "Asia", 3], ["Zhengzhou", "China", "Asia", 3],
  ["Changsha", "China", "Asia", 3], ["Kunming", "China", "Asia", 3],
  ["Fuzhou", "China", "Asia", 3], ["Xiamen", "China", "Asia", 2],
  ["Ningbo", "China", "Asia", 3], ["Wuxi", "China", "Asia", 3],
  ["Urumqi", "China", "Asia", 3], ["Sanya", "China", "Asia", 3],
  ["Lhasa", "China", "Asia", 3], ["Zhuhai", "China", "Asia", 3],
  ["Guilin", "China", "Asia", 3], ["Quanzhou", "China", "Asia", 3],
  ["Nanchang", "China", "Asia", 3], ["Hefei", "China", "Asia", 3],
  ["Daegu", "South Korea", "Asia", 3], ["Daejeon", "South Korea", "Asia", 3],
  ["Gwangju", "South Korea", "Asia", 3], ["Suwon", "South Korea", "Asia", 4],
  ["Ulsan", "South Korea", "Asia", 4], ["Jeju City", "South Korea", "Asia", 3],
  ["Jeonju", "South Korea", "Asia", 4], ["Kanpur", "India", "Asia", 3],
  ["Nagpur", "India", "Asia", 3], ["Indore", "India", "Asia", 3],
  ["Bhopal", "India", "Asia", 3], ["Patna", "India", "Asia", 3],
  ["Kochi", "India", "Asia", 3], ["Visakhapatnam", "India", "Asia", 3],
  ["Agra", "India", "Asia", 2], ["Amritsar", "India", "Asia", 3],
  ["Chandigarh", "India", "Asia", 3], ["Mysore", "India", "Asia", 3],
  ["Udaipur", "India", "Asia", 3], ["Jodhpur", "India", "Asia", 3],
  ["Madurai", "India", "Asia", 4], ["Srinagar", "India", "Asia", 3],
  ["Bhubaneswar", "India", "Asia", 3], ["Dehradun", "India", "Asia", 3],
  ["Rawalpindi", "Pakistan", "Asia", 3], ["Peshawar", "Pakistan", "Asia", 3],
  ["Quetta", "Pakistan", "Asia", 4], ["Sylhet", "Bangladesh", "Asia", 4],
  ["Khulna", "Bangladesh", "Asia", 4], ["Kandy", "Sri Lanka", "Asia", 3],
  ["Galle", "Sri Lanka", "Asia", 3], ["Pokhara", "Nepal", "Asia", 3],
  ["Malé", "Maldives", "Asia", 3], ["Pattaya", "Thailand", "Asia", 3],
  ["Phuket", "Thailand", "Asia", 3], ["Ayutthaya", "Thailand", "Asia", 3],
  ["Chiang Rai", "Thailand", "Asia", 4], ["Hue", "Vietnam", "Asia", 3],
  ["Nha Trang", "Vietnam", "Asia", 3], ["Hai Phong", "Vietnam", "Asia", 3],
  ["Ha Long", "Vietnam", "Asia", 3], ["Semarang", "Indonesia", "Asia", 3],
  ["Makassar", "Indonesia", "Asia", 3], ["Yogyakarta", "Indonesia", "Asia", 2],
  ["Palembang", "Indonesia", "Asia", 3], ["Malang", "Indonesia", "Asia", 3],
  ["Johor Bahru", "Malaysia", "Asia", 3], ["Ipoh", "Malaysia", "Asia", 3],
  ["Malacca", "Malaysia", "Asia", 3], ["Kota Kinabalu", "Malaysia", "Asia", 3],
  ["Kuching", "Malaysia", "Asia", 3], ["Putrajaya", "Malaysia", "Asia", 3],
  ["Quezon City", "Philippines", "Asia", 3], ["Makati", "Philippines", "Asia", 2],
  ["Iloilo City", "Philippines", "Asia", 3], ["Baguio", "Philippines", "Asia", 3],
  ["Naypyidaw", "Myanmar", "Asia", 3], ["Bagan", "Myanmar", "Asia", 3],
  ["Siem Reap", "Cambodia", "Asia", 3], ["Luang Prabang", "Laos", "Asia", 3],
  ["Bandar Seri Begawan", "Brunei", "Asia", 3], ["Tabriz", "Iran", "Asia", 3],
  ["Yazd", "Iran", "Asia", 3], ["Karaj", "Iran", "Asia", 4],
  ["Basra", "Iraq", "Asia", 3], ["Erbil", "Iraq", "Asia", 3],
  ["Mosul", "Iraq", "Asia", 3], ["Medina", "Saudi Arabia", "Asia", 2],
  ["Dammam", "Saudi Arabia", "Asia", 3], ["Sharjah", "United Arab Emirates", "Asia", 3],
  ["Al Ain", "United Arab Emirates", "Asia", 4], ["Nazareth", "Israel", "Asia", 4],
  ["Salalah", "Oman", "Asia", 4], ["Sanaa", "Yemen", "Asia", 3],
  ["Batumi", "Georgia", "Asia", 3], ["Kabul", "Afghanistan", "Asia", 2],
  ["Herat", "Afghanistan", "Asia", 4], ["Shymkent", "Kazakhstan", "Asia", 4],
  ["Osh", "Kyrgyzstan", "Asia", 4],

  // ---------- Americas ----------
  ["Raleigh", "United States", "Americas", 3], ["Omaha", "United States", "Americas", 4],
  ["Colorado Springs", "United States", "Americas", 4], ["Tulsa", "United States", "Americas", 4],
  ["Wichita", "United States", "Americas", 4], ["Saint Paul", "United States", "Americas", 3],
  ["Newark", "United States", "Americas", 3], ["Orlando", "United States", "Americas", 3],
  ["Jersey City", "United States", "Americas", 3], ["Fort Worth", "United States", "Americas", 3],
  ["El Paso", "United States", "Americas", 3], ["Long Beach", "United States", "Americas", 3],
  ["Louisville", "United States", "Americas", 3], ["Richmond", "United States", "Americas", 3],
  ["Boise", "United States", "Americas", 4], ["Reno", "United States", "Americas", 4],
  ["Savannah", "United States", "Americas", 3], ["Charleston", "United States", "Americas", 3],
  ["Providence", "United States", "Americas", 3], ["Knoxville", "United States", "Americas", 4],
  ["Albany", "United States", "Americas", 4], ["Rochester", "United States", "Americas", 4],
  ["Fort Lauderdale", "United States", "Americas", 3], ["Santa Fe", "United States", "Americas", 3],
  ["Tacoma", "United States", "Americas", 4], ["Spokane", "United States", "Americas", 4],
  ["Mississauga", "Canada", "Americas", 3], ["Surrey", "Canada", "Americas", 4],
  ["Laval", "Canada", "Americas", 4], ["Gatineau", "Canada", "Americas", 4],
  ["Windsor", "Canada", "Americas", 4], ["Regina", "Canada", "Americas", 4],
  ["St. John's", "Canada", "Americas", 3], ["Kelowna", "Canada", "Americas", 4],
  ["Querétaro", "Mexico", "Americas", 3], ["Acapulco", "Mexico", "Americas", 3],
  ["Veracruz", "Mexico", "Americas", 3], ["San Luis Potosí", "Mexico", "Americas", 3],
  ["Aguascalientes", "Mexico", "Americas", 4], ["Mexicali", "Mexico", "Americas", 4],
  ["Culiacán", "Mexico", "Americas", 4], ["Hermosillo", "Mexico", "Americas", 4],
  ["Chihuahua", "Mexico", "Americas", 3], ["Morelia", "Mexico", "Americas", 3],
  ["Mazatlán", "Mexico", "Americas", 3], ["Guanajuato", "Mexico", "Americas", 3],
  ["Puerto Vallarta", "Mexico", "Americas", 3], ["Guatemala City", "Guatemala", "Americas", 2],
  ["Antigua Guatemala", "Guatemala", "Americas", 3], ["San Salvador", "El Salvador", "Americas", 2],
  ["Tegucigalpa", "Honduras", "Americas", 2], ["San Pedro Sula", "Honduras", "Americas", 3],
  ["Managua", "Nicaragua", "Americas", 2], ["Belize City", "Belize", "Americas", 3],
  ["Port-au-Prince", "Haiti", "Americas", 2], ["Bridgetown", "Barbados", "Americas", 3],
  ["Port of Spain", "Trinidad and Tobago", "Americas", 3], ["Willemstad", "Curaçao", "Americas", 3],
  ["Oranjestad", "Aruba", "Americas", 4], ["Campinas", "Brazil", "Americas", 3],
  ["Florianópolis", "Brazil", "Americas", 3], ["Natal", "Brazil", "Americas", 3],
  ["Maceió", "Brazil", "Americas", 3], ["Santos", "Brazil", "Americas", 3],
  ["São Luís", "Brazil", "Americas", 3], ["Londrina", "Brazil", "Americas", 4],
  ["Joinville", "Brazil", "Americas", 4], ["Niterói", "Brazil", "Americas", 4],
  ["Uberlândia", "Brazil", "Americas", 4], ["Salta", "Argentina", "Americas", 3],
  ["San Miguel de Tucumán", "Argentina", "Americas", 3], ["Bariloche", "Argentina", "Americas", 3],
  ["Ushuaia", "Argentina", "Americas", 3], ["Viña del Mar", "Chile", "Americas", 3],
  ["Iquique", "Chile", "Americas", 4], ["Punta Arenas", "Chile", "Americas", 3],
  ["Puerto Montt", "Chile", "Americas", 4], ["Iquitos", "Peru", "Americas", 3],
  ["Piura", "Peru", "Americas", 4], ["Chiclayo", "Peru", "Americas", 4],
  ["Santa Marta", "Colombia", "Americas", 3], ["Pereira", "Colombia", "Americas", 4],
  ["Manizales", "Colombia", "Americas", 4], ["Cuenca", "Ecuador", "Americas", 3],
  ["Santa Cruz de la Sierra", "Bolivia", "Americas", 3], ["Cochabamba", "Bolivia", "Americas", 3],
  ["Punta del Este", "Uruguay", "Americas", 3], ["Paramaribo", "Suriname", "Americas", 3],
  ["Georgetown", "Guyana", "Americas", 3],

  // ---------- Africa ----------
  ["Giza", "Egypt", "Africa", 2], ["Luxor", "Egypt", "Africa", 2],
  ["Aswan", "Egypt", "Africa", 3], ["Port Said", "Egypt", "Africa", 3],
  ["Sharm El Sheikh", "Egypt", "Africa", 3], ["Hurghada", "Egypt", "Africa", 3],
  ["Tangier", "Morocco", "Africa", 3], ["Agadir", "Morocco", "Africa", 3],
  ["Meknes", "Morocco", "Africa", 3], ["Essaouira", "Morocco", "Africa", 3],
  ["Chefchaouen", "Morocco", "Africa", 3], ["Oran", "Algeria", "Africa", 3],
  ["Constantine", "Algeria", "Africa", 3], ["Annaba", "Algeria", "Africa", 4],
  ["Sousse", "Tunisia", "Africa", 3], ["Sfax", "Tunisia", "Africa", 4],
  ["Benghazi", "Libya", "Africa", 3], ["Kano", "Nigeria", "Africa", 3],
  ["Kaduna", "Nigeria", "Africa", 4], ["Benin City", "Nigeria", "Africa", 4],
  ["Kumasi", "Ghana", "Africa", 3], ["Tamale", "Ghana", "Africa", 4],
  ["Port Elizabeth", "South Africa", "Africa", 3], ["Bloemfontein", "South Africa", "Africa", 3],
  ["East London", "South Africa", "Africa", 4], ["Stellenbosch", "South Africa", "Africa", 3],
  ["Soweto", "South Africa", "Africa", 3], ["Kisumu", "Kenya", "Africa", 3],
  ["Nakuru", "Kenya", "Africa", 4], ["Dire Dawa", "Ethiopia", "Africa", 4],
  ["Bahir Dar", "Ethiopia", "Africa", 4], ["Gondar", "Ethiopia", "Africa", 4],
  ["Dodoma", "Tanzania", "Africa", 3], ["Zanzibar City", "Tanzania", "Africa", 3],
  ["Arusha", "Tanzania", "Africa", 3], ["Entebbe", "Uganda", "Africa", 4],
  ["Saint-Louis", "Senegal", "Africa", 4], ["Beira", "Mozambique", "Africa", 4],
  ["Livingstone", "Zambia", "Africa", 3], ["Bulawayo", "Zimbabwe", "Africa", 4],
  ["Victoria Falls", "Zimbabwe", "Africa", 3], ["Swakopmund", "Namibia", "Africa", 3],
  ["Goma", "Democratic Republic of the Congo", "Africa", 4], ["Omdurman", "Sudan", "Africa", 4],
  ["Port Louis", "Mauritius", "Africa", 3], ["Victoria", "Seychelles", "Africa", 4],
  ["Asmara", "Eritrea", "Africa", 3], ["Mogadishu", "Somalia", "Africa", 3],
  ["Lilongwe", "Malawi", "Africa", 4], ["Blantyre", "Malawi", "Africa", 4],
  ["Porto-Novo", "Benin", "Africa", 4], ["N'Djamena", "Chad", "Africa", 4],
  ["Nouakchott", "Mauritania", "Africa", 4], ["Monrovia", "Liberia", "Africa", 3],
  ["Djibouti City", "Djibouti", "Africa", 3], ["Praia", "Cape Verde", "Africa", 4],
  ["Mbabane", "Eswatini", "Africa", 4], ["Maseru", "Lesotho", "Africa", 4],
  ["Bujumbura", "Burundi", "Africa", 4], ["Banjul", "Gambia", "Africa", 4],

  // ---------- Oceania ----------
  ["Cairns", "Australia", "Oceania", 3], ["Townsville", "Australia", "Oceania", 4],
  ["Toowoomba", "Australia", "Oceania", 4], ["Ballarat", "Australia", "Oceania", 4],
  ["Bendigo", "Australia", "Oceania", 4], ["Launceston", "Australia", "Oceania", 4],
  ["Mackay", "Australia", "Oceania", 4], ["Alice Springs", "Australia", "Oceania", 3],
  ["Sunshine Coast", "Australia", "Oceania", 3], ["Bunbury", "Australia", "Oceania", 4],
  ["Napier", "New Zealand", "Oceania", 4], ["Nelson", "New Zealand", "Oceania", 4],
  ["Queenstown", "New Zealand", "Oceania", 3], ["Rotorua", "New Zealand", "Oceania", 3],
  ["Palmerston North", "New Zealand", "Oceania", 4], ["New Plymouth", "New Zealand", "Oceania", 4],
  ["Nadi", "Fiji", "Oceania", 4], ["Lae", "Papua New Guinea", "Oceania", 4],
  ["Nuku'alofa", "Tonga", "Oceania", 4], ["Port Vila", "Vanuatu", "Oceania", 4],

  // ===== second batch (secondary cities with strong Commons coverage) =====
  // -- Europe --
  ["Wolverhampton", "United Kingdom", "Europe", 4], ["Reading", "United Kingdom", "Europe", 4],
  ["Milton Keynes", "United Kingdom", "Europe", 4], ["Gloucester", "United Kingdom", "Europe", 4],
  ["Sunderland", "United Kingdom", "Europe", 4], ["Bradford", "United Kingdom", "Europe", 4],
  ["Chester", "United Kingdom", "Europe", 4], ["Canterbury", "United Kingdom", "Europe", 3],
  ["Preston", "United Kingdom", "Europe", 4], ["Wuppertal", "Germany", "Europe", 4],
  ["Braunschweig", "Germany", "Europe", 4], ["Magdeburg", "Germany", "Europe", 4],
  ["Halle", "Germany", "Europe", 4], ["Saarbrücken", "Germany", "Europe", 4],
  ["Osnabrück", "Germany", "Europe", 4], ["Oldenburg", "Germany", "Europe", 4],
  ["Krefeld", "Germany", "Europe", 4], ["Darmstadt", "Germany", "Europe", 4],
  ["Kassel", "Germany", "Europe", 4], ["Limoges", "France", "Europe", 4],
  ["Amiens", "France", "Europe", 4], ["Besançon", "France", "Europe", 4],
  ["Mulhouse", "France", "Europe", 4], ["Pau", "France", "Europe", 4],
  ["Bayonne", "France", "Europe", 4], ["Poitiers", "France", "Europe", 4],
  ["Valence", "France", "Europe", 4], ["Troyes", "France", "Europe", 4],
  ["Treviso", "Italy", "Europe", 4], ["Udine", "Italy", "Europe", 4],
  ["Sassari", "Italy", "Europe", 4], ["Foggia", "Italy", "Europe", 4],
  ["Latina", "Italy", "Europe", 4], ["Monza", "Italy", "Europe", 4],
  ["Pescara", "Italy", "Europe", 4], ["Livorno", "Italy", "Europe", 4],
  ["Cremona", "Italy", "Europe", 4], ["Burgos", "Spain", "Europe", 4],
  ["Logroño", "Spain", "Europe", 4], ["Albacete", "Spain", "Europe", 4],
  ["Castellón", "Spain", "Europe", 4], ["Huelva", "Spain", "Europe", 4],
  ["Lleida", "Spain", "Europe", 4], ["Ourense", "Spain", "Europe", 4],
  ["Almería", "Spain", "Europe", 4], ["Cáceres", "Spain", "Europe", 4],
  ["Breda", "Netherlands", "Europe", 4], ["Tilburg", "Netherlands", "Europe", 4],
  ["Arnhem", "Netherlands", "Europe", 4], ["Amersfoort", "Netherlands", "Europe", 4],
  ["Zwolle", "Netherlands", "Europe", 4], ["Zug", "Switzerland", "Europe", 4],
  ["Fribourg", "Switzerland", "Europe", 4], ["Neuchâtel", "Switzerland", "Europe", 4],
  ["Jönköping", "Sweden", "Europe", 4], ["Gävle", "Sweden", "Europe", 4],
  ["Sundsvall", "Sweden", "Europe", 4], ["Borås", "Sweden", "Europe", 4],
  ["Fredrikstad", "Norway", "Europe", 4], ["Sandnes", "Norway", "Europe", 4],
  ["Tønsberg", "Norway", "Europe", 4], ["Lahti", "Finland", "Europe", 4],
  ["Kuopio", "Finland", "Europe", 4], ["Pori", "Finland", "Europe", 4],
  ["Vaasa", "Finland", "Europe", 4], ["Kielce", "Poland", "Europe", 4],
  ["Częstochowa", "Poland", "Europe", 4], ["Radom", "Poland", "Europe", 4],
  ["Olsztyn", "Poland", "Europe", 4], ["Rzeszów", "Poland", "Europe", 4],
  ["Volos", "Greece", "Europe", 4], ["Larissa", "Greece", "Europe", 4],
  ["Ioannina", "Greece", "Europe", 4], ["Craiova", "Romania", "Europe", 4],
  ["Galați", "Romania", "Europe", 4], ["Oradea", "Romania", "Europe", 4],
  ["Ploiești", "Romania", "Europe", 4], ["Tyumen", "Russia", "Europe", 4],
  ["Tomsk", "Russia", "Europe", 4], ["Yaroslavl", "Russia", "Europe", 4],
  ["Voronezh", "Russia", "Europe", 4], ["Saratov", "Russia", "Europe", 4],
  ["Perm", "Russia", "Europe", 4], ["Ufa", "Russia", "Europe", 4],
  ["Omsk", "Russia", "Europe", 4], ["Chelyabinsk", "Russia", "Europe", 4],
  ["Setúbal", "Portugal", "Europe", 4], ["Guimarães", "Portugal", "Europe", 4],
  ["Villach", "Austria", "Europe", 4], ["Randers", "Denmark", "Europe", 4],
  ["Győr", "Hungary", "Europe", 4], ["Subotica", "Serbia", "Europe", 4],
  ["Ruse", "Bulgaria", "Europe", 4],
  // -- Asia --
  ["Oita", "Japan", "Asia", 4], ["Miyazaki", "Japan", "Asia", 4],
  ["Toyama", "Japan", "Asia", 4], ["Gifu", "Japan", "Asia", 4],
  ["Nagano", "Japan", "Asia", 4], ["Matsumoto", "Japan", "Asia", 4],
  ["Aomori", "Japan", "Asia", 4], ["Akita", "Japan", "Asia", 4],
  ["Morioka", "Japan", "Asia", 4], ["Utsunomiya", "Japan", "Asia", 4],
  ["Wakayama", "Japan", "Asia", 4], ["Tangshan", "China", "Asia", 4],
  ["Yantai", "China", "Asia", 4], ["Weifang", "China", "Asia", 4],
  ["Shaoxing", "China", "Asia", 4], ["Wenzhou", "China", "Asia", 4],
  ["Nantong", "China", "Asia", 4], ["Luoyang", "China", "Asia", 4],
  ["Datong", "China", "Asia", 4], ["Baotou", "China", "Asia", 4],
  ["Hohhot", "China", "Asia", 4], ["Yinchuan", "China", "Asia", 4],
  ["Vadodara", "India", "Asia", 4], ["Coimbatore", "India", "Asia", 4],
  ["Thiruvananthapuram", "India", "Asia", 4], ["Guwahati", "India", "Asia", 4],
  ["Nashik", "India", "Asia", 4], ["Ludhiana", "India", "Asia", 4],
  ["Rajkot", "India", "Asia", 4], ["Ranchi", "India", "Asia", 4],
  ["Raipur", "India", "Asia", 4], ["Jamshedpur", "India", "Asia", 4],
  ["Vijayawada", "India", "Asia", 4], ["Tiruchirappalli", "India", "Asia", 4],
  ["Panaji", "India", "Asia", 4], ["Padang", "Indonesia", "Asia", 4],
  ["Pekanbaru", "Indonesia", "Asia", 4], ["Manado", "Indonesia", "Asia", 4],
  ["Pontianak", "Indonesia", "Asia", 4], ["Balikpapan", "Indonesia", "Asia", 4],
  ["Surakarta", "Indonesia", "Asia", 4], ["Cagayan de Oro", "Philippines", "Asia", 4],
  ["Bacolod", "Philippines", "Asia", 4], ["General Santos", "Philippines", "Asia", 4],
  ["Puerto Princesa", "Philippines", "Asia", 4], ["Vigan", "Philippines", "Asia", 4],
  ["Da Lat", "Vietnam", "Asia", 4], ["Vung Tau", "Vietnam", "Asia", 4],
  ["Can Tho", "Vietnam", "Asia", 4], ["Hat Yai", "Thailand", "Asia", 4],
  ["Khon Kaen", "Thailand", "Asia", 4], ["Udon Thani", "Thailand", "Asia", 4],
  ["Nakhon Ratchasima", "Thailand", "Asia", 4], ["Cheongju", "South Korea", "Asia", 4],
  ["Pohang", "South Korea", "Asia", 4], ["Changwon", "South Korea", "Asia", 4],
  ["Ahvaz", "Iran", "Asia", 4], ["Rasht", "Iran", "Asia", 4],
  ["Kerman", "Iran", "Asia", 4], ["Qom", "Iran", "Asia", 4],
  ["Samsun", "Turkey", "Asia", 4], ["Denizli", "Turkey", "Asia", 4],
  ["Mersin", "Turkey", "Asia", 4], ["Şanlıurfa", "Turkey", "Asia", 4],
  ["Diyarbakır", "Turkey", "Asia", 4], ["Malatya", "Turkey", "Asia", 4],
  ["Taif", "Saudi Arabia", "Asia", 4], ["Abha", "Saudi Arabia", "Asia", 4],
  ["Tabuk", "Saudi Arabia", "Asia", 4], ["Khobar", "Saudi Arabia", "Asia", 4],
  ["Ajman", "United Arab Emirates", "Asia", 4], ["Ras al-Khaimah", "United Arab Emirates", "Asia", 4],
  ["Najaf", "Iraq", "Asia", 4], ["Karbala", "Iraq", "Asia", 4],
  ["Kirkuk", "Iraq", "Asia", 4], ["Sialkot", "Pakistan", "Asia", 4],
  ["Gujranwala", "Pakistan", "Asia", 4], ["Karaganda", "Kazakhstan", "Asia", 4],
  ["Aktobe", "Kazakhstan", "Asia", 4], ["Andijan", "Uzbekistan", "Asia", 4],
  ["Namangan", "Uzbekistan", "Asia", 4],
  // -- Americas --
  ["Scottsdale", "United States", "Americas", 4], ["Glendale", "United States", "Americas", 4],
  ["Irvine", "United States", "Americas", 4], ["Chesapeake", "United States", "Americas", 4],
  ["Little Rock", "United States", "Americas", 4], ["Mobile", "United States", "Americas", 4],
  ["Montgomery", "United States", "Americas", 4], ["Huntsville", "United States", "Americas", 4],
  ["Shreveport", "United States", "Americas", 4], ["Worcester", "United States", "Americas", 4],
  ["New Haven", "United States", "Americas", 4], ["Allentown", "United States", "Americas", 4],
  ["Lansing", "United States", "Americas", 4], ["Fort Wayne", "United States", "Americas", 4],
  ["Des Moines", "United States", "Americas", 4], ["Sioux Falls", "United States", "Americas", 4],
  ["Fargo", "United States", "Americas", 4], ["Eugene", "United States", "Americas", 4],
  ["Provo", "United States", "Americas", 4], ["Bellevue", "United States", "Americas", 4],
  ["Tallahassee", "United States", "Americas", 4], ["Greensboro", "United States", "Americas", 4],
  ["Sherbrooke", "Canada", "Americas", 4], ["Thunder Bay", "Canada", "Americas", 4],
  ["Sudbury", "Canada", "Americas", 4], ["Moncton", "Canada", "Americas", 4],
  ["Fredericton", "Canada", "Americas", 4], ["Charlottetown", "Canada", "Americas", 4],
  ["Yellowknife", "Canada", "Americas", 4], ["Abbotsford", "Canada", "Americas", 4],
  ["Tampico", "Mexico", "Americas", 4], ["Saltillo", "Mexico", "Americas", 4],
  ["Durango", "Mexico", "Americas", 4], ["Ensenada", "Mexico", "Americas", 4],
  ["Villahermosa", "Mexico", "Americas", 4], ["Campeche", "Mexico", "Americas", 4],
  ["Tepic", "Mexico", "Americas", 4], ["Zacatecas", "Mexico", "Americas", 4],
  ["Caxias do Sul", "Brazil", "Americas", 4], ["Juiz de Fora", "Brazil", "Americas", 4],
  ["Feira de Santana", "Brazil", "Americas", 4], ["Petrópolis", "Brazil", "Americas", 4],
  ["Olinda", "Brazil", "Americas", 4], ["Blumenau", "Brazil", "Americas", 4],
  ["Sorocaba", "Brazil", "Americas", 4], ["Paraná", "Argentina", "Americas", 4],
  ["Corrientes", "Argentina", "Americas", 4], ["Posadas", "Argentina", "Americas", 4],
  ["Neuquén", "Argentina", "Americas", 4], ["Temuco", "Chile", "Americas", 4],
  ["La Serena", "Chile", "Americas", 4], ["Arica", "Chile", "Americas", 4],
  ["Valdivia", "Chile", "Americas", 4], ["Ibagué", "Colombia", "Americas", 4],
  ["Villavicencio", "Colombia", "Americas", 4], ["Popayán", "Colombia", "Americas", 4],
  ["Armenia", "Colombia", "Americas", 4], ["Tacna", "Peru", "Americas", 4],
  ["Huancayo", "Peru", "Americas", 4], ["Montego Bay", "Jamaica", "Americas", 4],
  ["Colón", "Panama", "Americas", 4], ["Castries", "Saint Lucia", "Americas", 4],
  ["St. George's", "Grenada", "Americas", 4], ["Basseterre", "Saint Kitts and Nevis", "Americas", 4],
  ["Kingstown", "Saint Vincent and the Grenadines", "Americas", 4],
  // -- Africa --
  ["Mansoura", "Egypt", "Africa", 4], ["Tanta", "Egypt", "Africa", 4],
  ["Suez", "Egypt", "Africa", 4], ["Ismailia", "Egypt", "Africa", 4],
  ["Asyut", "Egypt", "Africa", 4], ["Oujda", "Morocco", "Africa", 4],
  ["Kenitra", "Morocco", "Africa", 4], ["Tetouan", "Morocco", "Africa", 4],
  ["El Jadida", "Morocco", "Africa", 4], ["Setif", "Algeria", "Africa", 4],
  ["Tlemcen", "Algeria", "Africa", 4], ["Jos", "Nigeria", "Africa", 4],
  ["Ilorin", "Nigeria", "Africa", 4], ["Onitsha", "Nigeria", "Africa", 4],
  ["Abeokuta", "Nigeria", "Africa", 4], ["Pietermaritzburg", "South Africa", "Africa", 4],
  ["Kimberley", "South Africa", "Africa", 4], ["Polokwane", "South Africa", "Africa", 4],
  ["Nelspruit", "South Africa", "Africa", 4], ["Eldoret", "Kenya", "Africa", 4],
  ["Malindi", "Kenya", "Africa", 4], ["Cape Coast", "Ghana", "Africa", 4],
  ["Takoradi", "Ghana", "Africa", 4], ["Mwanza", "Tanzania", "Africa", 4],
  ["Bamenda", "Cameroon", "Africa", 4], ["Bafoussam", "Cameroon", "Africa", 4],
  ["Mekelle", "Ethiopia", "Africa", 4], ["Hawassa", "Ethiopia", "Africa", 4],
  ["Huambo", "Angola", "Africa", 4], ["Benguela", "Angola", "Africa", 4],
  ["Kisangani", "Democratic Republic of the Congo", "Africa", 4], ["Ndola", "Zambia", "Africa", 4],
  ["Kitwe", "Zambia", "Africa", 4], ["Toamasina", "Madagascar", "Africa", 4],
  ["Port Sudan", "Sudan", "Africa", 4], ["Juba", "South Sudan", "Africa", 4],
  ["Touba", "Senegal", "Africa", 4], ["Thiès", "Senegal", "Africa", 4],
  ["Nampula", "Mozambique", "Africa", 4], ["Walvis Bay", "Namibia", "Africa", 4],
  ["Mutare", "Zimbabwe", "Africa", 4], ["Jinja", "Uganda", "Africa", 4],
  // -- Oceania --
  ["Geraldton", "Australia", "Oceania", 4], ["Kalgoorlie", "Australia", "Oceania", 4],
  ["Mildura", "Australia", "Oceania", 4], ["Wagga Wagga", "Australia", "Oceania", 4],
  ["Bundaberg", "Australia", "Oceania", 4], ["Gladstone", "Australia", "Oceania", 4],
  ["Port Macquarie", "Australia", "Oceania", 4], ["Dubbo", "Australia", "Oceania", 4],
  ["Devonport", "Australia", "Oceania", 4], ["Mount Gambier", "Australia", "Oceania", 4],
  ["Whangarei", "New Zealand", "Oceania", 4], ["Gisborne", "New Zealand", "Oceania", 4],
  ["Timaru", "New Zealand", "Oceania", 4], ["Taupo", "New Zealand", "Oceania", 4],
  ["Lautoka", "Fiji", "Oceania", 4], ["Tarawa", "Kiribati", "Oceania", 4],
  ["Majuro", "Marshall Islands", "Oceania", 4], ["Hagåtña", "Guam", "Oceania", 4],
  ["Avarua", "Cook Islands", "Oceania", 4],
];
for (const [name, country, continent, tier] of MORE) cities.push({ name, country, continent, tier });

// Slugify utility (used to generate stable ids)
export function slug(s) {
  return s
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

// Attach a stable id to every entry
for (const c of cities) {
  c.id = `${slug(c.name)}-${slug(c.country)}`;
}
