// Curated list of cities for the birds-eye-view quiz.
// tier: 1 = globally iconic, 2 = major, 3 = regional, 4 = niche
// commonsCategory overrides the default "Aerial photographs of <name>" when needed.
// wikipediaTitle overrides the default <name> for the Wikipedia REST API lookup.

export const cities = [
  // ---------- Europe ----------
  { name: "London", country: "United Kingdom", continent: "Europe", tier: 1 },
  { name: "Paris", country: "France", continent: "Europe", tier: 1 },
  { name: "Rome", country: "Italy", continent: "Europe", tier: 1 },
  { name: "Berlin", country: "Germany", continent: "Europe", tier: 1 },
  { name: "Madrid", country: "Spain", continent: "Europe", tier: 1 },
  { name: "Barcelona", country: "Spain", continent: "Europe", tier: 1 },
  { name: "Amsterdam", country: "Netherlands", continent: "Europe", tier: 1 },
  { name: "Vienna", country: "Austria", continent: "Europe", tier: 1 },
  { name: "Prague", country: "Czechia", continent: "Europe", tier: 1 },
  { name: "Athens", country: "Greece", continent: "Europe", tier: 1 },
  { name: "Lisbon", country: "Portugal", continent: "Europe", tier: 1 },
  { name: "Dublin", country: "Ireland", continent: "Europe", tier: 1 },
  { name: "Stockholm", country: "Sweden", continent: "Europe", tier: 1 },
  { name: "Copenhagen", country: "Denmark", continent: "Europe", tier: 1 },
  { name: "Helsinki", country: "Finland", continent: "Europe", tier: 2 },
  { name: "Oslo", country: "Norway", continent: "Europe", tier: 2 },
  { name: "Warsaw", country: "Poland", continent: "Europe", tier: 2 },
  { name: "Budapest", country: "Hungary", continent: "Europe", tier: 1 },
  { name: "Moscow", country: "Russia", continent: "Europe", tier: 1 },
  { name: "Saint Petersburg", country: "Russia", continent: "Europe", tier: 1 },
  { name: "Istanbul", country: "Turkey", continent: "Europe", tier: 1 },
  { name: "Munich", country: "Germany", continent: "Europe", tier: 2 },
  { name: "Hamburg", country: "Germany", continent: "Europe", tier: 2 },
  { name: "Frankfurt", country: "Germany", continent: "Europe", tier: 2, wikipediaTitle: "Frankfurt" },
  { name: "Cologne", country: "Germany", continent: "Europe", tier: 2 },
  { name: "Stuttgart", country: "Germany", continent: "Europe", tier: 3 },
  { name: "Düsseldorf", country: "Germany", continent: "Europe", tier: 3 },
  { name: "Milan", country: "Italy", continent: "Europe", tier: 1 },
  { name: "Naples", country: "Italy", continent: "Europe", tier: 2 },
  { name: "Florence", country: "Italy", continent: "Europe", tier: 1 },
  { name: "Venice", country: "Italy", continent: "Europe", tier: 1 },
  { name: "Bologna", country: "Italy", continent: "Europe", tier: 3 },
  { name: "Turin", country: "Italy", continent: "Europe", tier: 3 },
  { name: "Genoa", country: "Italy", continent: "Europe", tier: 3 },
  { name: "Palermo", country: "Italy", continent: "Europe", tier: 3 },
  { name: "Brussels", country: "Belgium", continent: "Europe", tier: 2 },
  { name: "Antwerp", country: "Belgium", continent: "Europe", tier: 3 },
  { name: "Zurich", country: "Switzerland", continent: "Europe", tier: 2 },
  { name: "Geneva", country: "Switzerland", continent: "Europe", tier: 2 },
  { name: "Bern", country: "Switzerland", continent: "Europe", tier: 3 },
  { name: "Edinburgh", country: "United Kingdom", continent: "Europe", tier: 1 },
  { name: "Manchester", country: "United Kingdom", continent: "Europe", tier: 2 },
  { name: "Birmingham", country: "United Kingdom", continent: "Europe", tier: 2 },
  { name: "Glasgow", country: "United Kingdom", continent: "Europe", tier: 2 },
  { name: "Liverpool", country: "United Kingdom", continent: "Europe", tier: 2 },
  { name: "Bristol", country: "United Kingdom", continent: "Europe", tier: 3 },
  { name: "Leeds", country: "United Kingdom", continent: "Europe", tier: 3 },
  { name: "Cardiff", country: "United Kingdom", continent: "Europe", tier: 3 },
  { name: "Belfast", country: "United Kingdom", continent: "Europe", tier: 3 },
  { name: "Newcastle upon Tyne", country: "United Kingdom", continent: "Europe", tier: 4 },
  { name: "Lyon", country: "France", continent: "Europe", tier: 2 },
  { name: "Marseille", country: "France", continent: "Europe", tier: 2 },
  { name: "Toulouse", country: "France", continent: "Europe", tier: 3 },
  { name: "Nice", country: "France", continent: "Europe", tier: 2, wikipediaTitle: "Nice" },
  { name: "Bordeaux", country: "France", continent: "Europe", tier: 3 },
  { name: "Strasbourg", country: "France", continent: "Europe", tier: 3 },
  { name: "Seville", country: "Spain", continent: "Europe", tier: 2, wikipediaTitle: "Seville" },
  { name: "Valencia", country: "Spain", continent: "Europe", tier: 2 },
  { name: "Bilbao", country: "Spain", continent: "Europe", tier: 3 },
  { name: "Malaga", country: "Spain", continent: "Europe", tier: 3, wikipediaTitle: "Málaga" },
  { name: "Granada", country: "Spain", continent: "Europe", tier: 3 },
  { name: "Porto", country: "Portugal", continent: "Europe", tier: 2 },
  { name: "Reykjavik", country: "Iceland", continent: "Europe", tier: 2, wikipediaTitle: "Reykjavík" },
  { name: "Bucharest", country: "Romania", continent: "Europe", tier: 2 },
  { name: "Sofia", country: "Bulgaria", continent: "Europe", tier: 2 },
  { name: "Belgrade", country: "Serbia", continent: "Europe", tier: 2 },
  { name: "Zagreb", country: "Croatia", continent: "Europe", tier: 3 },
  { name: "Ljubljana", country: "Slovenia", continent: "Europe", tier: 3 },
  { name: "Sarajevo", country: "Bosnia and Herzegovina", continent: "Europe", tier: 3 },
  { name: "Skopje", country: "North Macedonia", continent: "Europe", tier: 4 },
  { name: "Tirana", country: "Albania", continent: "Europe", tier: 4 },
  { name: "Tallinn", country: "Estonia", continent: "Europe", tier: 3 },
  { name: "Riga", country: "Latvia", continent: "Europe", tier: 3 },
  { name: "Vilnius", country: "Lithuania", continent: "Europe", tier: 3 },
  { name: "Minsk", country: "Belarus", continent: "Europe", tier: 3 },
  { name: "Kyiv", country: "Ukraine", continent: "Europe", tier: 2 },
  { name: "Lviv", country: "Ukraine", continent: "Europe", tier: 3 },
  { name: "Krakow", country: "Poland", continent: "Europe", tier: 2, wikipediaTitle: "Kraków" },
  { name: "Gdansk", country: "Poland", continent: "Europe", tier: 3, wikipediaTitle: "Gdańsk" },
  { name: "Wroclaw", country: "Poland", continent: "Europe", tier: 3, wikipediaTitle: "Wrocław" },
  { name: "Poznan", country: "Poland", continent: "Europe", tier: 4, wikipediaTitle: "Poznań" },
  { name: "Bratislava", country: "Slovakia", continent: "Europe", tier: 3 },
  { name: "Luxembourg City", country: "Luxembourg", continent: "Europe", tier: 4, wikipediaTitle: "Luxembourg City" },
  { name: "Monaco", country: "Monaco", continent: "Europe", tier: 2 },
  { name: "Valletta", country: "Malta", continent: "Europe", tier: 4 },
  { name: "Nicosia", country: "Cyprus", continent: "Europe", tier: 4 },
  { name: "Rotterdam", country: "Netherlands", continent: "Europe", tier: 3 },
  { name: "The Hague", country: "Netherlands", continent: "Europe", tier: 3 },
  { name: "Utrecht", country: "Netherlands", continent: "Europe", tier: 4 },
  { name: "Gothenburg", country: "Sweden", continent: "Europe", tier: 4 },
  { name: "Bergen", country: "Norway", continent: "Europe", tier: 4 },
  { name: "Aarhus", country: "Denmark", continent: "Europe", tier: 4 },

  // ---------- Asia ----------
  { name: "Tokyo", country: "Japan", continent: "Asia", tier: 1 },
  { name: "Osaka", country: "Japan", continent: "Asia", tier: 2 },
  { name: "Kyoto", country: "Japan", continent: "Asia", tier: 2 },
  { name: "Yokohama", country: "Japan", continent: "Asia", tier: 3 },
  { name: "Nagoya", country: "Japan", continent: "Asia", tier: 3 },
  { name: "Sapporo", country: "Japan", continent: "Asia", tier: 3 },
  { name: "Fukuoka", country: "Japan", continent: "Asia", tier: 4 },
  { name: "Hiroshima", country: "Japan", continent: "Asia", tier: 3 },
  { name: "Beijing", country: "China", continent: "Asia", tier: 1 },
  { name: "Shanghai", country: "China", continent: "Asia", tier: 1 },
  { name: "Hong Kong", country: "China", continent: "Asia", tier: 1 },
  { name: "Guangzhou", country: "China", continent: "Asia", tier: 2 },
  { name: "Shenzhen", country: "China", continent: "Asia", tier: 2 },
  { name: "Chengdu", country: "China", continent: "Asia", tier: 3 },
  { name: "Chongqing", country: "China", continent: "Asia", tier: 3 },
  { name: "Wuhan", country: "China", continent: "Asia", tier: 3 },
  { name: "Tianjin", country: "China", continent: "Asia", tier: 3 },
  { name: "Xi'an", country: "China", continent: "Asia", tier: 3 },
  { name: "Hangzhou", country: "China", continent: "Asia", tier: 3 },
  { name: "Nanjing", country: "China", continent: "Asia", tier: 3 },
  { name: "Macau", country: "China", continent: "Asia", tier: 2 },
  { name: "Taipei", country: "Taiwan", continent: "Asia", tier: 2 },
  { name: "Kaohsiung", country: "Taiwan", continent: "Asia", tier: 4 },
  { name: "Seoul", country: "South Korea", continent: "Asia", tier: 1 },
  { name: "Busan", country: "South Korea", continent: "Asia", tier: 3 },
  { name: "Incheon", country: "South Korea", continent: "Asia", tier: 4 },
  { name: "Pyongyang", country: "North Korea", continent: "Asia", tier: 3 },
  { name: "Singapore", country: "Singapore", continent: "Asia", tier: 1 },
  { name: "Kuala Lumpur", country: "Malaysia", continent: "Asia", tier: 2 },
  { name: "George Town", country: "Malaysia", continent: "Asia", tier: 4, wikipediaTitle: "George Town, Penang" },
  { name: "Bangkok", country: "Thailand", continent: "Asia", tier: 1 },
  { name: "Chiang Mai", country: "Thailand", continent: "Asia", tier: 4 },
  { name: "Jakarta", country: "Indonesia", continent: "Asia", tier: 2 },
  { name: "Surabaya", country: "Indonesia", continent: "Asia", tier: 4 },
  { name: "Bali", country: "Indonesia", continent: "Asia", tier: 3, wikipediaTitle: "Denpasar" },
  { name: "Manila", country: "Philippines", continent: "Asia", tier: 2 },
  { name: "Cebu City", country: "Philippines", continent: "Asia", tier: 4 },
  { name: "Ho Chi Minh City", country: "Vietnam", continent: "Asia", tier: 2 },
  { name: "Hanoi", country: "Vietnam", continent: "Asia", tier: 2 },
  { name: "Phnom Penh", country: "Cambodia", continent: "Asia", tier: 3 },
  { name: "Vientiane", country: "Laos", continent: "Asia", tier: 4 },
  { name: "Yangon", country: "Myanmar", continent: "Asia", tier: 3 },
  { name: "Mumbai", country: "India", continent: "Asia", tier: 1 },
  { name: "Delhi", country: "India", continent: "Asia", tier: 1 },
  { name: "Kolkata", country: "India", continent: "Asia", tier: 2 },
  { name: "Chennai", country: "India", continent: "Asia", tier: 2 },
  { name: "Bangalore", country: "India", continent: "Asia", tier: 2 },
  { name: "Hyderabad", country: "India", continent: "Asia", tier: 2 },
  { name: "Ahmedabad", country: "India", continent: "Asia", tier: 3 },
  { name: "Pune", country: "India", continent: "Asia", tier: 3 },
  { name: "Jaipur", country: "India", continent: "Asia", tier: 3 },
  { name: "Karachi", country: "Pakistan", continent: "Asia", tier: 2 },
  { name: "Lahore", country: "Pakistan", continent: "Asia", tier: 3 },
  { name: "Islamabad", country: "Pakistan", continent: "Asia", tier: 3 },
  { name: "Dhaka", country: "Bangladesh", continent: "Asia", tier: 2 },
  { name: "Colombo", country: "Sri Lanka", continent: "Asia", tier: 3 },
  { name: "Kathmandu", country: "Nepal", continent: "Asia", tier: 3 },
  { name: "Thimphu", country: "Bhutan", continent: "Asia", tier: 4 },
  { name: "Tehran", country: "Iran", continent: "Asia", tier: 2 },
  { name: "Isfahan", country: "Iran", continent: "Asia", tier: 4 },
  { name: "Baghdad", country: "Iraq", continent: "Asia", tier: 2 },
  { name: "Riyadh", country: "Saudi Arabia", continent: "Asia", tier: 2 },
  { name: "Jeddah", country: "Saudi Arabia", continent: "Asia", tier: 3 },
  { name: "Mecca", country: "Saudi Arabia", continent: "Asia", tier: 2 },
  { name: "Dubai", country: "United Arab Emirates", continent: "Asia", tier: 1 },
  { name: "Abu Dhabi", country: "United Arab Emirates", continent: "Asia", tier: 2 },
  { name: "Doha", country: "Qatar", continent: "Asia", tier: 2 },
  { name: "Kuwait City", country: "Kuwait", continent: "Asia", tier: 3 },
  { name: "Muscat", country: "Oman", continent: "Asia", tier: 3 },
  { name: "Manama", country: "Bahrain", continent: "Asia", tier: 4 },
  { name: "Beirut", country: "Lebanon", continent: "Asia", tier: 2 },
  { name: "Damascus", country: "Syria", continent: "Asia", tier: 2 },
  { name: "Amman", country: "Jordan", continent: "Asia", tier: 3 },
  { name: "Jerusalem", country: "Israel", continent: "Asia", tier: 1 },
  { name: "Tel Aviv", country: "Israel", continent: "Asia", tier: 2 },
  { name: "Ulaanbaatar", country: "Mongolia", continent: "Asia", tier: 3 },
  { name: "Almaty", country: "Kazakhstan", continent: "Asia", tier: 3 },
  { name: "Astana", country: "Kazakhstan", continent: "Asia", tier: 3 },
  { name: "Tashkent", country: "Uzbekistan", continent: "Asia", tier: 3 },
  { name: "Samarkand", country: "Uzbekistan", continent: "Asia", tier: 4 },
  { name: "Baku", country: "Azerbaijan", continent: "Asia", tier: 3 },
  { name: "Yerevan", country: "Armenia", continent: "Asia", tier: 3 },
  { name: "Tbilisi", country: "Georgia", continent: "Asia", tier: 3 },

  // ---------- Americas ----------
  { name: "New York City", country: "United States", continent: "Americas", tier: 1, wikipediaTitle: "New York City" },
  { name: "Los Angeles", country: "United States", continent: "Americas", tier: 1 },
  { name: "Chicago", country: "United States", continent: "Americas", tier: 1 },
  { name: "Houston", country: "United States", continent: "Americas", tier: 2 },
  { name: "Phoenix", country: "United States", continent: "Americas", tier: 3, wikipediaTitle: "Phoenix, Arizona" },
  { name: "Philadelphia", country: "United States", continent: "Americas", tier: 2 },
  { name: "San Antonio", country: "United States", continent: "Americas", tier: 3 },
  { name: "San Diego", country: "United States", continent: "Americas", tier: 2 },
  { name: "Dallas", country: "United States", continent: "Americas", tier: 2 },
  { name: "San Jose", country: "United States", continent: "Americas", tier: 3, wikipediaTitle: "San Jose, California" },
  { name: "Austin", country: "United States", continent: "Americas", tier: 3, wikipediaTitle: "Austin, Texas" },
  { name: "Jacksonville", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Jacksonville, Florida" },
  { name: "Columbus", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Columbus, Ohio" },
  { name: "Charlotte", country: "United States", continent: "Americas", tier: 3, wikipediaTitle: "Charlotte, North Carolina" },
  { name: "San Francisco", country: "United States", continent: "Americas", tier: 1 },
  { name: "Indianapolis", country: "United States", continent: "Americas", tier: 4 },
  { name: "Seattle", country: "United States", continent: "Americas", tier: 1 },
  { name: "Denver", country: "United States", continent: "Americas", tier: 2 },
  { name: "Washington, D.C.", country: "United States", continent: "Americas", tier: 1, wikipediaTitle: "Washington, D.C." },
  { name: "Boston", country: "United States", continent: "Americas", tier: 1 },
  { name: "Nashville", country: "United States", continent: "Americas", tier: 3, wikipediaTitle: "Nashville, Tennessee" },
  { name: "Baltimore", country: "United States", continent: "Americas", tier: 3 },
  { name: "Portland", country: "United States", continent: "Americas", tier: 2, wikipediaTitle: "Portland, Oregon" },
  { name: "Las Vegas", country: "United States", continent: "Americas", tier: 1 },
  { name: "Miami", country: "United States", continent: "Americas", tier: 1 },
  { name: "Atlanta", country: "United States", continent: "Americas", tier: 2 },
  { name: "Detroit", country: "United States", continent: "Americas", tier: 2 },
  { name: "Minneapolis", country: "United States", continent: "Americas", tier: 3 },
  { name: "Tampa", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Tampa, Florida" },
  { name: "New Orleans", country: "United States", continent: "Americas", tier: 2 },
  { name: "Pittsburgh", country: "United States", continent: "Americas", tier: 3 },
  { name: "Cincinnati", country: "United States", continent: "Americas", tier: 4 },
  { name: "Cleveland", country: "United States", continent: "Americas", tier: 3, wikipediaTitle: "Cleveland" },
  { name: "St. Louis", country: "United States", continent: "Americas", tier: 3 },
  { name: "Kansas City", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Kansas City, Missouri" },
  { name: "Salt Lake City", country: "United States", continent: "Americas", tier: 3 },
  { name: "Honolulu", country: "United States", continent: "Americas", tier: 2 },
  { name: "Anchorage", country: "United States", continent: "Americas", tier: 4 },
  { name: "Toronto", country: "Canada", continent: "Americas", tier: 1 },
  { name: "Vancouver", country: "Canada", continent: "Americas", tier: 1 },
  { name: "Montreal", country: "Canada", continent: "Americas", tier: 1 },
  { name: "Calgary", country: "Canada", continent: "Americas", tier: 3 },
  { name: "Ottawa", country: "Canada", continent: "Americas", tier: 2 },
  { name: "Edmonton", country: "Canada", continent: "Americas", tier: 3 },
  { name: "Winnipeg", country: "Canada", continent: "Americas", tier: 4 },
  { name: "Quebec City", country: "Canada", continent: "Americas", tier: 3 },
  { name: "Halifax", country: "Canada", continent: "Americas", tier: 4, wikipediaTitle: "Halifax, Nova Scotia" },
  { name: "Mexico City", country: "Mexico", continent: "Americas", tier: 1 },
  { name: "Guadalajara", country: "Mexico", continent: "Americas", tier: 3 },
  { name: "Monterrey", country: "Mexico", continent: "Americas", tier: 3 },
  { name: "Tijuana", country: "Mexico", continent: "Americas", tier: 3 },
  { name: "Cancun", country: "Mexico", continent: "Americas", tier: 3, wikipediaTitle: "Cancún" },
  { name: "Puebla", country: "Mexico", continent: "Americas", tier: 4 },
  { name: "Oaxaca", country: "Mexico", continent: "Americas", tier: 4, wikipediaTitle: "Oaxaca City" },
  { name: "São Paulo", country: "Brazil", continent: "Americas", tier: 1 },
  { name: "Rio de Janeiro", country: "Brazil", continent: "Americas", tier: 1 },
  { name: "Brasília", country: "Brazil", continent: "Americas", tier: 2 },
  { name: "Salvador", country: "Brazil", continent: "Americas", tier: 3, wikipediaTitle: "Salvador, Bahia" },
  { name: "Fortaleza", country: "Brazil", continent: "Americas", tier: 3 },
  { name: "Belo Horizonte", country: "Brazil", continent: "Americas", tier: 3 },
  { name: "Manaus", country: "Brazil", continent: "Americas", tier: 3 },
  { name: "Porto Alegre", country: "Brazil", continent: "Americas", tier: 3 },
  { name: "Recife", country: "Brazil", continent: "Americas", tier: 3 },
  { name: "Curitiba", country: "Brazil", continent: "Americas", tier: 4 },
  { name: "Buenos Aires", country: "Argentina", continent: "Americas", tier: 1 },
  { name: "Córdoba", country: "Argentina", continent: "Americas", tier: 4, wikipediaTitle: "Córdoba, Argentina" },
  { name: "Rosario", country: "Argentina", continent: "Americas", tier: 4 },
  { name: "Mendoza", country: "Argentina", continent: "Americas", tier: 4, wikipediaTitle: "Mendoza, Argentina" },
  { name: "Santiago", country: "Chile", continent: "Americas", tier: 2, wikipediaTitle: "Santiago" },
  { name: "Valparaíso", country: "Chile", continent: "Americas", tier: 4 },
  { name: "Lima", country: "Peru", continent: "Americas", tier: 2 },
  { name: "Cusco", country: "Peru", continent: "Americas", tier: 3 },
  { name: "La Paz", country: "Bolivia", continent: "Americas", tier: 3 },
  { name: "Sucre", country: "Bolivia", continent: "Americas", tier: 4 },
  { name: "Quito", country: "Ecuador", continent: "Americas", tier: 3 },
  { name: "Guayaquil", country: "Ecuador", continent: "Americas", tier: 4 },
  { name: "Bogotá", country: "Colombia", continent: "Americas", tier: 2 },
  { name: "Medellín", country: "Colombia", continent: "Americas", tier: 2 },
  { name: "Cartagena", country: "Colombia", continent: "Americas", tier: 3, wikipediaTitle: "Cartagena, Colombia" },
  { name: "Cali", country: "Colombia", continent: "Americas", tier: 4 },
  { name: "Caracas", country: "Venezuela", continent: "Americas", tier: 2 },
  { name: "Montevideo", country: "Uruguay", continent: "Americas", tier: 3 },
  { name: "Asunción", country: "Paraguay", continent: "Americas", tier: 4 },
  { name: "Panama City", country: "Panama", continent: "Americas", tier: 2 },
  { name: "San José", country: "Costa Rica", continent: "Americas", tier: 3, wikipediaTitle: "San José, Costa Rica" },
  { name: "Havana", country: "Cuba", continent: "Americas", tier: 2 },
  { name: "Santo Domingo", country: "Dominican Republic", continent: "Americas", tier: 3 },
  { name: "Kingston", country: "Jamaica", continent: "Americas", tier: 3, wikipediaTitle: "Kingston, Jamaica" },
  { name: "San Juan", country: "Puerto Rico", continent: "Americas", tier: 3, wikipediaTitle: "San Juan, Puerto Rico" },
  { name: "Nassau", country: "Bahamas", continent: "Americas", tier: 4, wikipediaTitle: "Nassau, Bahamas" },

  // ---------- Africa ----------
  { name: "Cairo", country: "Egypt", continent: "Africa", tier: 1 },
  { name: "Alexandria", country: "Egypt", continent: "Africa", tier: 3 },
  { name: "Lagos", country: "Nigeria", continent: "Africa", tier: 2 },
  { name: "Abuja", country: "Nigeria", continent: "Africa", tier: 4 },
  { name: "Kinshasa", country: "DR Congo", continent: "Africa", tier: 3 },
  { name: "Johannesburg", country: "South Africa", continent: "Africa", tier: 1 },
  { name: "Cape Town", country: "South Africa", continent: "Africa", tier: 1 },
  { name: "Durban", country: "South Africa", continent: "Africa", tier: 3 },
  { name: "Pretoria", country: "South Africa", continent: "Africa", tier: 3 },
  { name: "Nairobi", country: "Kenya", continent: "Africa", tier: 2 },
  { name: "Mombasa", country: "Kenya", continent: "Africa", tier: 4 },
  { name: "Addis Ababa", country: "Ethiopia", continent: "Africa", tier: 3 },
  { name: "Algiers", country: "Algeria", continent: "Africa", tier: 3 },
  { name: "Casablanca", country: "Morocco", continent: "Africa", tier: 2 },
  { name: "Marrakesh", country: "Morocco", continent: "Africa", tier: 2 },
  { name: "Rabat", country: "Morocco", continent: "Africa", tier: 3 },
  { name: "Fez", country: "Morocco", continent: "Africa", tier: 4 },
  { name: "Tunis", country: "Tunisia", continent: "Africa", tier: 3 },
  { name: "Tripoli", country: "Libya", continent: "Africa", tier: 3 },
  { name: "Khartoum", country: "Sudan", continent: "Africa", tier: 3 },
  { name: "Dakar", country: "Senegal", continent: "Africa", tier: 3 },
  { name: "Abidjan", country: "Ivory Coast", continent: "Africa", tier: 3 },
  { name: "Accra", country: "Ghana", continent: "Africa", tier: 3 },
  { name: "Lusaka", country: "Zambia", continent: "Africa", tier: 4 },
  { name: "Harare", country: "Zimbabwe", continent: "Africa", tier: 3 },
  { name: "Maputo", country: "Mozambique", continent: "Africa", tier: 4 },
  { name: "Luanda", country: "Angola", continent: "Africa", tier: 3 },
  { name: "Dar es Salaam", country: "Tanzania", continent: "Africa", tier: 3 },
  { name: "Kampala", country: "Uganda", continent: "Africa", tier: 3 },
  { name: "Kigali", country: "Rwanda", continent: "Africa", tier: 3 },
  { name: "Antananarivo", country: "Madagascar", continent: "Africa", tier: 4 },
  { name: "Windhoek", country: "Namibia", continent: "Africa", tier: 4 },
  { name: "Gaborone", country: "Botswana", continent: "Africa", tier: 4 },

  // ---------- Oceania ----------
  { name: "Sydney", country: "Australia", continent: "Oceania", tier: 1 },
  { name: "Melbourne", country: "Australia", continent: "Oceania", tier: 1 },
  { name: "Brisbane", country: "Australia", continent: "Oceania", tier: 2 },
  { name: "Perth", country: "Australia", continent: "Oceania", tier: 2, wikipediaTitle: "Perth" },
  { name: "Adelaide", country: "Australia", continent: "Oceania", tier: 3 },
  { name: "Canberra", country: "Australia", continent: "Oceania", tier: 2 },
  { name: "Hobart", country: "Australia", continent: "Oceania", tier: 4 },
  { name: "Gold Coast", country: "Australia", continent: "Oceania", tier: 3, wikipediaTitle: "Gold Coast, Queensland" },
  { name: "Auckland", country: "New Zealand", continent: "Oceania", tier: 2 },
  { name: "Wellington", country: "New Zealand", continent: "Oceania", tier: 3 },
  { name: "Christchurch", country: "New Zealand", continent: "Oceania", tier: 3 },
  { name: "Suva", country: "Fiji", continent: "Oceania", tier: 4 },
  { name: "Port Moresby", country: "Papua New Guinea", continent: "Oceania", tier: 4 },
  { name: "Honiara", country: "Solomon Islands", continent: "Oceania", tier: 4 },
  { name: "Apia", country: "Samoa", continent: "Oceania", tier: 4 },

  // ---------- Additional Europe ----------
  { name: "Salzburg", country: "Austria", continent: "Europe", tier: 3 },
  { name: "Innsbruck", country: "Austria", continent: "Europe", tier: 4 },
  { name: "Graz", country: "Austria", continent: "Europe", tier: 4 },
  { name: "Linz", country: "Austria", continent: "Europe", tier: 4 },
  { name: "Heidelberg", country: "Germany", continent: "Europe", tier: 3 },
  { name: "Dresden", country: "Germany", continent: "Europe", tier: 3 },
  { name: "Leipzig", country: "Germany", continent: "Europe", tier: 3 },
  { name: "Hannover", country: "Germany", continent: "Europe", tier: 4 },
  { name: "Bremen", country: "Germany", continent: "Europe", tier: 4 },
  { name: "Nuremberg", country: "Germany", continent: "Europe", tier: 3 },
  { name: "Montpellier", country: "France", continent: "Europe", tier: 4 },
  { name: "Rennes", country: "France", continent: "Europe", tier: 4 },
  { name: "Lille", country: "France", continent: "Europe", tier: 4 },
  { name: "Nantes", country: "France", continent: "Europe", tier: 4 },
  { name: "Catania", country: "Italy", continent: "Europe", tier: 4 },
  { name: "Verona", country: "Italy", continent: "Europe", tier: 4 },
  { name: "Padua", country: "Italy", continent: "Europe", tier: 4 },
  { name: "Pisa", country: "Italy", continent: "Europe", tier: 4 },
  { name: "Cluj-Napoca", country: "Romania", continent: "Europe", tier: 4 },
  { name: "Plovdiv", country: "Bulgaria", continent: "Europe", tier: 4 },
  { name: "Novi Sad", country: "Serbia", continent: "Europe", tier: 4 },
  { name: "Brno", country: "Czechia", continent: "Europe", tier: 4 },
  { name: "Pécs", country: "Hungary", continent: "Europe", tier: 4 },
  { name: "Debrecen", country: "Hungary", continent: "Europe", tier: 4 },
  { name: "Ghent", country: "Belgium", continent: "Europe", tier: 3 },
  { name: "Bruges", country: "Belgium", continent: "Europe", tier: 3 },
  { name: "Liège", country: "Belgium", continent: "Europe", tier: 4 },
  { name: "Basel", country: "Switzerland", continent: "Europe", tier: 3 },
  { name: "Lausanne", country: "Switzerland", continent: "Europe", tier: 4 },
  { name: "Cork", country: "Ireland", continent: "Europe", tier: 4 },
  { name: "Galway", country: "Ireland", continent: "Europe", tier: 4 },
  { name: "Aberdeen", country: "United Kingdom", continent: "Europe", tier: 4 },
  { name: "Sheffield", country: "United Kingdom", continent: "Europe", tier: 4 },
  { name: "Nottingham", country: "United Kingdom", continent: "Europe", tier: 4 },
  { name: "Trondheim", country: "Norway", continent: "Europe", tier: 4 },
  { name: "Stavanger", country: "Norway", continent: "Europe", tier: 4 },
  { name: "Malmö", country: "Sweden", continent: "Europe", tier: 4 },
  { name: "Uppsala", country: "Sweden", continent: "Europe", tier: 4 },
  { name: "Tampere", country: "Finland", continent: "Europe", tier: 4 },
  { name: "Turku", country: "Finland", continent: "Europe", tier: 4 },
  { name: "Odense", country: "Denmark", continent: "Europe", tier: 4 },

  // ---------- Additional Asia ----------
  { name: "Kobe", country: "Japan", continent: "Asia", tier: 3 },
  { name: "Sendai", country: "Japan", continent: "Asia", tier: 4 },
  { name: "Kanazawa", country: "Japan", continent: "Asia", tier: 4 },
  { name: "Nara", country: "Japan", continent: "Asia", tier: 4 },
  { name: "Suzhou", country: "China", continent: "Asia", tier: 3 },
  { name: "Qingdao", country: "China", continent: "Asia", tier: 4 },
  { name: "Dalian", country: "China", continent: "Asia", tier: 4 },
  { name: "Lucknow", country: "India", continent: "Asia", tier: 4 },
  { name: "Surat", country: "India", continent: "Asia", tier: 4 },
  { name: "Varanasi", country: "India", continent: "Asia", tier: 4 },
  { name: "Faisalabad", country: "Pakistan", continent: "Asia", tier: 4 },
  { name: "Multan", country: "Pakistan", continent: "Asia", tier: 4 },
  { name: "Chittagong", country: "Bangladesh", continent: "Asia", tier: 4 },
  { name: "Bandung", country: "Indonesia", continent: "Asia", tier: 4 },
  { name: "Medan", country: "Indonesia", continent: "Asia", tier: 4 },
  { name: "Davao", country: "Philippines", continent: "Asia", tier: 4, wikipediaTitle: "Davao City" },
  { name: "Da Nang", country: "Vietnam", continent: "Asia", tier: 4 },
  { name: "Mandalay", country: "Myanmar", continent: "Asia", tier: 4 },
  { name: "Mashhad", country: "Iran", continent: "Asia", tier: 4 },
  { name: "Shiraz", country: "Iran", continent: "Asia", tier: 4 },
  { name: "Aleppo", country: "Syria", continent: "Asia", tier: 4 },
  { name: "Haifa", country: "Israel", continent: "Asia", tier: 4 },
  { name: "Bukhara", country: "Uzbekistan", continent: "Asia", tier: 4 },
  { name: "Bishkek", country: "Kyrgyzstan", continent: "Asia", tier: 4 },
  { name: "Dushanbe", country: "Tajikistan", continent: "Asia", tier: 4 },
  { name: "Ashgabat", country: "Turkmenistan", continent: "Asia", tier: 4 },

  // ---------- Additional Americas ----------
  { name: "Memphis", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Memphis, Tennessee" },
  { name: "Milwaukee", country: "United States", continent: "Americas", tier: 4 },
  { name: "Albuquerque", country: "United States", continent: "Americas", tier: 4 },
  { name: "Oklahoma City", country: "United States", continent: "Americas", tier: 4 },
  { name: "Tucson", country: "United States", continent: "Americas", tier: 4 },
  { name: "Sacramento", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Sacramento, California" },
  { name: "Fresno", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Fresno, California" },
  { name: "Buffalo", country: "United States", continent: "Americas", tier: 4, wikipediaTitle: "Buffalo, New York" },
  { name: "Saskatoon", country: "Canada", continent: "Americas", tier: 4 },
  { name: "Hamilton", country: "Canada", continent: "Americas", tier: 4, wikipediaTitle: "Hamilton, Ontario" },
  { name: "Victoria", country: "Canada", continent: "Americas", tier: 4, wikipediaTitle: "Victoria, British Columbia" },
  { name: "Mérida", country: "Mexico", continent: "Americas", tier: 4, wikipediaTitle: "Mérida, Yucatán" },
  { name: "León", country: "Mexico", continent: "Americas", tier: 4, wikipediaTitle: "León, Guanajuato" },
  { name: "Belém", country: "Brazil", continent: "Americas", tier: 4 },
  { name: "Goiânia", country: "Brazil", continent: "Americas", tier: 4 },
  { name: "Vitória", country: "Brazil", continent: "Americas", tier: 4, wikipediaTitle: "Vitória, Espírito Santo" },
  { name: "La Plata", country: "Argentina", continent: "Americas", tier: 4 },
  { name: "Mar del Plata", country: "Argentina", continent: "Americas", tier: 4 },
  { name: "Antofagasta", country: "Chile", continent: "Americas", tier: 4 },
  { name: "Concepción", country: "Chile", continent: "Americas", tier: 4, wikipediaTitle: "Concepción, Chile" },
  { name: "Arequipa", country: "Peru", continent: "Americas", tier: 4 },
  { name: "Trujillo", country: "Peru", continent: "Americas", tier: 4, wikipediaTitle: "Trujillo, Peru" },
  { name: "Barranquilla", country: "Colombia", continent: "Americas", tier: 4 },
  { name: "Bucaramanga", country: "Colombia", continent: "Americas", tier: 4 },
  { name: "Maracaibo", country: "Venezuela", continent: "Americas", tier: 4 },

  // ---------- Additional Africa ----------
  { name: "Port Harcourt", country: "Nigeria", continent: "Africa", tier: 4 },
  { name: "Ibadan", country: "Nigeria", continent: "Africa", tier: 4 },
  { name: "Lubumbashi", country: "DR Congo", continent: "Africa", tier: 4 },
  { name: "Bamako", country: "Mali", continent: "Africa", tier: 4 },
  { name: "Niamey", country: "Niger", continent: "Africa", tier: 4 },
  { name: "Ouagadougou", country: "Burkina Faso", continent: "Africa", tier: 4 },
  { name: "Lomé", country: "Togo", continent: "Africa", tier: 4 },
  { name: "Cotonou", country: "Benin", continent: "Africa", tier: 4 },
  { name: "Conakry", country: "Guinea", continent: "Africa", tier: 4 },
  { name: "Freetown", country: "Sierra Leone", continent: "Africa", tier: 4 },
  { name: "Yaoundé", country: "Cameroon", continent: "Africa", tier: 4 },
  { name: "Douala", country: "Cameroon", continent: "Africa", tier: 4 },
  { name: "Brazzaville", country: "Republic of the Congo", continent: "Africa", tier: 4 },
  { name: "Libreville", country: "Gabon", continent: "Africa", tier: 4 },

  // ---------- Additional Oceania ----------
  { name: "Newcastle", country: "Australia", continent: "Oceania", tier: 4, wikipediaTitle: "Newcastle, New South Wales" },
  { name: "Wollongong", country: "Australia", continent: "Oceania", tier: 4 },
  { name: "Geelong", country: "Australia", continent: "Oceania", tier: 4 },
  { name: "Darwin", country: "Australia", continent: "Oceania", tier: 4, wikipediaTitle: "Darwin, Northern Territory" },
  { name: "Dunedin", country: "New Zealand", continent: "Oceania", tier: 4 },
  { name: "Tauranga", country: "New Zealand", continent: "Oceania", tier: 4 },
  { name: "Nouméa", country: "New Caledonia", continent: "Oceania", tier: 4 },
  { name: "Pago Pago", country: "American Samoa", continent: "Oceania", tier: 4 },
  { name: "Papeete", country: "French Polynesia", continent: "Oceania", tier: 4 },
];

// Slugify utility (used to generate stable ids)
export function slug(s) {
  return s
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

// Attach a stable id to every entry
for (const c of cities) {
  c.id = `${slug(c.name)}-${slug(c.country)}`;
}
